"""yang_web.core.misc_crypto 子模块 _cipher_types（自 misc_crypto.py 拆分，请勿手工重排）。"""

import os
import re
import base64 as b64
import binascii
import html as html_mod
import codecs
import urllib.parse
from pathlib import Path



# ═══════════════════════════════════════════
# 密码类型元数据
# ═══════════════════════════════════════════

CIPHER_TYPES = {
    "pigpen": {
        "name": "猪圈密码",
        "aliases": ["pigpen", "猪圈", "masonic", "pigpen_cipher"],
        "category": "图形替换",
        "encode": True, "decode": True,
        "image": "猪圈密码.png",
        "description": "共济会密码变体，用井字格+点标符号表示字母",
        "features": ["井字格图案", "带点/不带点", "4宫格变体"],
    },
    "bacon": {
        "name": "培根密码",
        "aliases": ["bacon", "培根", "baconian"],
        "category": "二进制替换",
        "encode": True, "decode": True,
        "image": "培根密码.jpg",
        "description": "用 A/B 5 位序列表示字母，可隐藏在大小写中",
        "features": ["AAAAA-ZZZZZ", "可隐藏在大小写/粗体中", "24/26字母版本"],
    },
    "polybius": {
        "name": "波利比奥斯棋盘",
        "aliases": ["polybius", "波利比奥斯", "polybius_square"],
        "category": "坐标替换",
        "encode": True, "decode": True,
        "image": "波利比奥斯棋盘.png",
        "description": "5×5 方阵行列坐标表示字母（I=J）",
        "features": ["11-55行列坐标", "I/J合并", "可扩展6x6含数字"],
    },
    "vigenere": {
        "name": "维吉尼亚密码",
        "aliases": ["vigenere", "维吉尼亚", "vig"],
        "category": "多表替换",
        "encode": True, "decode": True,
        "image": "维吉尼亚密码.png", "image2": "维吉尼亚密.png",
        "description": "使用密钥词的凯撒密码变体，多表替换",
        "features": ["密钥循环", "维吉尼亚方阵", "26×26表格"],
    },
    "caesar": {
        "name": "凯撒密码",
        "aliases": ["caesar", "凯撒", "caesar_shift"],
        "category": "单表替换",
        "encode": True, "decode": True,
        "image": "凯撒密码加密.jpg",
        "description": "固定偏移字母表，最古老的加密方式",
        "features": ["ROT13是其特例", "偏移量1-25", "可暴力枚举"],
    },
    "adfgx": {
        "name": "ADFGX 加密法",
        "aliases": ["adfgx", "adfgvx"],
        "category": "WWI 军事密码",
        "encode": True, "decode": True,
        "image": "ADFGX加密法.png",
        "description": "一战德军使用的双步加密：Polybius + 列置换",
        "features": ["仅用ADFGX字母", "5×5 Polybius", "需要密钥词"],
    },
    "qwe_keyboard": {
        "name": "QWE 键盘加密法",
        "aliases": ["qwe", "键盘QWE"],
        "category": "键盘映射",
        "encode": True, "decode": True,
        "image": "电脑键盘QWE加密法.jpg",
        "description": "QWERTY键盘顺序映射ABCD...",
        "features": ["Q=A, W=B, E=C...", "键盘布局", "简单替换"],
    },
    "keyboard_chessboard": {
        "name": "电脑键盘棋盘密码",
        "aliases": ["键盘棋盘", "keyboard_chess"],
        "category": "键盘映射",
        "encode": True, "decode": True,
        "image": "电脑键盘棋盘加密.jpg",
        "description": "键盘3行布局，行号+列号表示每个键",
        "features": ["Q=11, W=12...", "数字坐标", "3行键盘映射"],
    },
    "keyboard_coordinate": {
        "name": "电脑键盘坐标加密",
        "aliases": ["键盘坐标", "keyboard_coord"],
        "category": "键盘映射",
        "encode": True, "decode": True,
        "image": "电脑键盘坐标加密.jpg",
        "description": "用键盘矩阵行列坐标表示字母",
        "features": ["行号+列号", "双数字坐标", "参考图"],
    },
    "phone_keypad": {
        "name": "手机键盘密码",
        "aliases": ["phone", "手机键盘", "T9", "nokia"],
        "category": "数字映射",
        "encode": True, "decode": True,
        "image": "手机键盘加密解密.jpg",
        "description": "传统手机九宫格键盘，数字键+按键次数",
        "features": ["A=21, B=22...", "九宫格数字", "双位数字"],
    },
    "atbash": {
        "name": "埃特巴什码",
        "aliases": ["atbash", "埃特巴什"],
        "category": "单表替换",
        "encode": True, "decode": True,
        "image": None,
        "description": "字母表反转（A↔Z, B↔Y...），自反密码",
        "features": ["自反性", "A=Z, B=Y...", "最简单替换"],
    },
    "rail_fence": {
        "name": "栅栏密码",
        "aliases": ["rail_fence", "栅栏", "railfence"],
        "category": "置换",
        "encode": True, "decode": True,
        "image": None,
        "description": "之字形排列后按行读取",
        "features": ["之字形", "多层栅栏", "W型变体"],
    },
    "rot13": {
        "name": "ROT13",
        "aliases": ["rot13", "rot"],
        "category": "单表替换",
        "encode": True, "decode": True,
        "image": None,
        "description": "凯撒密码偏移13位特例，加密=解密",
        "features": ["自反性", "ROT5(数字)", "ROT47(ASCII)"],
    },
    "morse": {
        "name": "摩尔密码",
        "aliases": ["morse", "摩尔", "摩尔斯"],
        "category": "信号编码",
        "encode": True, "decode": True,
        "image": "摩尔密码加密与解密.jpg",
        "description": "点划信号编码，可表现为音频/灯光/文字",
        "features": [".- 长短信号", "可隐藏为音频", "空格/斜杠分隔"],
    },
    "pawnshat": {
        "name": "当铺密码",
        "aliases": ["当铺", "pawnshop", "pawn"],
        "category": "中文编码",
        "encode": True, "decode": True,
        "image": "当铺密码.jpg",
        "description": "汉字出头顶部笔画数映射数字0-9",
        "features": ["笔画头数", "口=0 由=1", "单数字编码"],
    },
    "number_coordinate": {
        "name": "数字坐标加密字母",
        "aliases": ["数字坐标", "number_coord"],
        "category": "坐标替换",
        "encode": True, "decode": True,
        "image": "数字坐标加密字母.png",
        "description": "字母网格坐标表示法，行号+列号",
        "features": ["XY坐标", "数字对", "参考图"],
    },
    "alphabet_order": {
        "name": "字母表顺序加密",
        "aliases": ["字母顺序", "alphabet_order"],
        "category": "数字映射",
        "encode": True, "decode": True,
        "image": "字母表顺序加密法和反字母表加密法和小键盘加密法.jpg",
        "description": "A=1, B=2...的简单数字对应",
        "features": ["A=1 B=2...", "反字母A=26", "小键盘映射"],
    },
    "standard_galactic": {
        "name": "标准银河字母",
        "aliases": ["SGA", "标准银河", "galactic", "enchanting_table"],
        "category": "符号替换",
        "encode": True, "decode": True,
        "image": "标准银河字母.png",
        "description": "Minecraft 附魔台文字，风格化字母替换",
        "features": ["Minecraft风格", "特殊符号字符", "Unicode"],
    },
    "binary": {
        "name": "二进制加密",
        "aliases": ["binary", "二进制", "2进制"],
        "category": "进制编码",
        "encode": True, "decode": True,
        "image": "二进制加密解密.png",
        "description": "ASCII/Unicode 字符的二进制表示",
        "features": ["7位/8位", "空格分隔", "可配合其他编码"],
    },
    "reverse": {
        "name": "倒序加密",
        "aliases": ["reverse", "倒序", "倒叙", "反转"],
        "category": "置换",
        "encode": True, "decode": True,
        "image": "倒叙加密解密.png",
        "description": "字符串直接反转，最简单的置换操作",
        "features": ["ABC→CBA", "可单词/句子", "非全反转注意"],
    },
    "jefferson_wheel": {
        "name": "托马斯·杰斐逊转轮密码",
        "aliases": ["jefferson", "转轮", "rotor", "轮转"],
        "category": "多表替换",
        "encode": True, "decode": True,
        "image": None,
        "description": "多轮盘密码机，密钥是轮盘使用顺序",
        "features": ["14个轮盘", "密钥控制顺序", "破解需遍历"],
    },
    "fes_hieroglyph": {
        "name": "菲斯象形文字",
        "aliases": ["菲斯", "fes", "hieroglyph"],
        "category": "符号替换",
        "encode": False, "decode": False,
        "image": "非斯的象形文字翻译图.png",
        "description": "图形符号对应字母的替换密码（仅参考图）",
        "features": ["象形图→字母", "视觉参考", "需手动对照"],
    },
    "blue_punch_card": {
        "name": "蓝色打孔卡",
        "aliases": ["punchcard", "打孔卡", "blue_punch"],
        "category": "编码参考",
        "encode": False, "decode": False,
        "image": "Blue-punch-card-front-horiz.png",
        "description": "IBM 打孔卡编码参考图，二进制存储的早期形式",
        "features": ["IBM格式", "80列", "矩形孔"],
    },
    # ── 基础编码 ──
    "base64": {
        "name": "Base64 编码",
        "aliases": ["base64", "b64"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "最常见的二进制→文本编码，结尾常有=填充",
        "features": ["A-Za-z0-9+/", "= 填充", "CTF 出场率最高"],
    },
    "base32": {
        "name": "Base32 编码",
        "aliases": ["base32", "b32"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "A-Z2-7 字符集，每5bit一组",
        "features": ["A-Z2-7", "= 填充到8的倍数", "全大写字母"],
    },
    "base16": {
        "name": "Base16 / Hex 编码",
        "aliases": ["hex", "base16", "十六进制"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "每字节→两位十六进制数（00-FF）",
        "features": ["0-9A-F", "偶数长度", "可0x前缀"],
    },
    "base58": {
        "name": "Base58 编码",
        "aliases": ["base58", "b58", "bitcoin"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "去除了易混淆字符的编码（无0OIl），Bitcoin地址使用",
        "features": ["无0OIl", "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"],
    },
    "base85": {
        "name": "Base85 / ASCII85",
        "aliases": ["base85", "b85", "ascii85"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "Adobe PostScript/PDF 使用的编码，~>结尾",
        "features": ["~> 结尾", "含特殊字符", "PDF/PostScript"],
    },
    "url_encode": {
        "name": "URL 编码",
        "aliases": ["url", "urlencode", "percent"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "%xx 格式，常用于Web传参",
        "features": ["% 百分号", "%xx 十六进制", "空格→%20或+"],
    },
    "html_entity": {
        "name": "HTML 实体编码",
        "aliases": ["html", "entity", "htmlentity"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "&amp; &lt; &#x27; 等形式，用于HTML/XSS",
        "features": ["& 开头 ; 结尾", "&#数字;", "&#x十六进制;"],
    },
    "unicode_escape": {
        "name": "Unicode 转义",
        "aliases": ["unicode", "uescape", "\\u"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "\\uXXXX 或 \\UXXXXXXXX 格式",
        "features": ["\\u 前缀", "4位/8位十六进制", "JSON/JS常用"],
    },
    "binary_str": {
        "name": "二进制字符串",
        "aliases": ["binary", "bin", "0101"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "每8位一组 0/1 表示一个ASCII字符",
        "features": ["0和1", "8位一组", "空格分隔"],
    },
    "octal_str": {
        "name": "八进制字符串",
        "aliases": ["octal", "oct", "八进制"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "\\ooo 格式，每3位八进制表示一个字符",
        "features": ["0-7 数字", "\\ 前缀", "3位一组"],
    },
    "decimal_str": {
        "name": "十进制ASCII码",
        "aliases": ["decimal", "dec", "ascii"],
        "category": "基础编码",
        "encode": True, "decode": True,
        "image": None,
        "description": "空格分隔的10进制数字，每个表示一个ASCII字符",
        "features": ["数字 32-126", "空格分隔", "ASCII表"],
    },
}
